### ISSUE TITLE
Incorrect integer value: 'null' for column 'xxx' at row 1

### ISSUE THREAD

**Issue by cjj137783** [apache/incubator-shardingsphere#2336] opened 2019-05-07 05:25 UTC
hello , I have a problem when I insert a row , below is my sql , the  sharding column is user_id

```
insert into log_user_key_action_1 (id, user_id,exchange_id ) 
values (575292640792121344, 112243515, null ) ;
```
the exchange_id is int in mysql , and got an error message 'Incorrect integer value: 'null' for column 'exchange_id' at row 1' , but I can execute in my Sub-table like this :

```
insert into log_user_key_action_1 (id, user_id,exchange_id ) 
values (575292640792121344, 112243515, null ) ;
```

**Comment by tristaZero** [comment] 2019-05-08 06:48
Hi, thanks for your issue. Please answer the following question:
1. Do you use Sharding-JDBC or Sharding-Proxy?
2. What version of ShardingSphere do you use?
3. Can you provide the complete error log?
@cjj137783

**Comment by tristaZero** [comment] 2019-05-19 01:30
@cjj137783 Hi, i am waiting your reply.
I will close this issue next Monday, if you do not come back until that day.

**Comment by tristaZero** [comment] 2019-05-21 02:10
Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Closed by tristaZero** 2019-05-21 02:11 UTC
Labels: investigate
