### ISSUE TITLE
when the tables in the DB is too much, the sharding init so slow

### ISSUE THREAD

**Issue by Erzhoumu** [apache/incubator-shardingsphere#2962] opened 2019-09-02 15:41 UTC
HI, When the tables in my DB are too much, the sharding will start too slow to init the metadata. but most of the table meta is the same,  if this process can be simpler and faster.

**Comment by siweizuse** [comment] 2019-09-03 03:36
i have same issues.
some people say can switch check.table.metadata.enabled:false.
but i dont know how to switch check.table.metadata.enabled:false.

**Comment by taojintianxia** [comment] 2019-09-03 11:54
```yaml
props:
  check.table.metadata.enabled: true
```
is that the root cause ?

**Comment by Erzhoumu** [comment] 2019-09-04 00:56
<prop key="executor.size">100</prop>
     <prop key="check.table.metadata.enabled">false</prop>
with this config, about 2000 tables in tht DB, init need about 5-10 min in a cheap mac.

**Comment by taojintianxia** [comment] 2019-09-04 03:05
dude, I tried to create 20,000 tables on my poor Mac, even it becomes so slowly when I execute *show tables* command. however, it just takes 2 or 3 seconds for ss example execution.

would you please provide a way to reproduce your issue, so people could easily understand

**Comment by Erzhoumu** [comment] 2019-09-04 08:56
![image](https://user-images.githubusercontent.com/10809138/64240568-af6e4800-cf34-11e9-9ecd-9830a37fcebc.png)
![image](https://user-images.githubusercontent.com/10809138/64240635-d0cf3400-cf34-11e9-94dd-87949e842a8b.png)

when debug, this place cost much time about 3m.
<prop key="check.table.metadata.enabled">false</prop>
 with this config, it still loaded meta data.

**Comment by taojintianxia** [comment] 2019-09-11 23:39
hi there, do you still work on this issue ?

**Comment by Erzhoumu** [comment] 2019-09-13 09:13
yes, trying to load faster.

**Comment by siweizuse** [comment] 2019-09-15 11:14
> dude, I tried to create 20,000 tables on my poor Mac, even it becomes so slowly when I execute _show tables_ command. however, it just takes 2 or 3 seconds for ss example execution.
> 
> would you please provide a way to reproduce your issue, so people could easily understand

I don't know why you load so fast.I don't have so much tables,but it still cost about 3m to load.just like his screenshot.

**Comment by taojintianxia** [comment] 2019-09-16 01:29
> > dude, I tried to create 20,000 tables on my poor Mac, even it becomes so slowly when I execute _show tables_ command. however, it just takes 2 or 3 seconds for ss example execution.
> > would you please provide a way to reproduce your issue, so people could easily understand
> 
> I don't know why you load so fast.I don't have so much tables,but it still cost about 3m to load.just like his screenshot.

I'll try that again

**Comment by Erzhoumu** [comment] 2019-09-16 03:36
4.0.0-RC1

**Comment by taojintianxia** [comment] 2019-09-20 04:51
> 4.0.0-RC1

That's it .... seems that this has been fixed in 4.0.0-RC2

**Closed** 2019-09-21 02:28 UTC
Labels: volunteer wanted

**Comment by Erzhoumu** [comment] 2019-09-24 09:57
4.0.0-RC2 is also slow wa~ our db is on the cloud and using blb, is that influenced?

**Comment by CatDogZ** [comment] 2019-12-09 08:48
@Erzhoumu Hi， bro, i have the same problem, do u fix it?

**Comment by Fermiz** [comment] 2020-02-21 08:13
Is there any solutions?
