### ISSUE TITLE
proxy-4.0.1 return wrong result when varchar value NULL in hibernate.

### ISSUE THREAD

**Issue by wangjing112** [apache/incubator-shardingsphere#4707] opened 2020-03-11 06:16 UTC
sharding-proxy-4.0.1
when use hibernate query from 2 table1 like:
![image](https://user-images.githubusercontent.com/51982240/76387529-26800f80-63a2-11ea-9d2d-d53ffae1f26f.png)
then 3 times querys from proxy return:

query1 table1 
[{"chapterId":1,"dailyData":"","gold":285212672,"id":36030446286411906,"openData":"{\"id\":1,\"lv\":0}]\u0002[]\u0000\u0000\u0000\u0000\u0000.1.65.103:61108\u0000^Β\u0001\u0000\u0000\u0000\u0000^Β\u0001\u0000\u0000\u0000\u0000�\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","overData":"","roleId":36030446286411906,"status":0},{"chapterId":101,"dailyData":"","gold":352321536,"id":36030446286411906,"openData":"{\"id\":10101,\"lv\":0}]\u0002[]\u0000\u0000\u0000\u0000\u00005.103:61108\u0000^Β\u0001\u0000\u0000\u0000\u0000^Β\u0001\u0000\u0000\u0000\u0000�\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","overData":"","roleId":36030446286411906,"status":0},{"chapterId":102,"dailyData":"","gold":352321536,"id":36030446286411906,"openData":"{\"id\":10201,\"lv\":0}]\u0002[]\u0000\u0000\u0000\u0000\u00005.103:61108\u0000^Β\u0001\u0000\u0000\u0000\u0000^Β\u0001\u0000\u0000\u0000\u0000�\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","overData":"","roleId":36030446286411906,"status":0}]

query2 table2
[{"extData":"","id":36030446286411906,"packetData":"[{\"id\":10001,\"no\":1,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10002,\"no\":2,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":202},{\"args\":[],\"id\":301}]}},{\"id\":10003,\"no\":3,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":102},{\"args\":[],\"id\":201},{\"args\":[],\"id\":302}]}},{\"id\":10006,\"no\":4,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10007,\"no\":5,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10008,\"no\":6,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10009,\"no\":7,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10014,\"no\":8,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10015,\"no\":9,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10016,\"no\":10,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10017,\"no\":11,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10018,\"no\":12,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10019,\"no\":13,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20001,\"no\":14,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20002,\"no\":15,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20003,\"no\":16,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20004,\"no\":17,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20005,\"no\":18,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20006,\"no\":19,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20007,\"no\":20,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20008,\"no\":21,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20009,\"no\":22,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20010,\"no\":23,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20011,\"no\":24,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20012,\"no\":25,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20013,\"no\":26,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}}]","roleId":36030446286411906,"size":0,"type":0},{"extData":"","id":36030446286411906,"packetData":"[{\"c\":10,\"i\":100},{\"c\":10,\"i\":101}]","roleId":36030446286411906,"size":0,"type":1},{"extData":"","id":36030446286411906,"packetData":"[{\"a\":\"2:2|4:4|3:2|5:2\",\"c\":1,\"i\":20001,\"ma\":\"1:1\",\"no\":1,\"set\":3},{\"a\":\"3:4|5:2|1:4|4:2\",\"c\":1,\"i\":20002,\"ma\":\"1:2\",\"no\":2,\"set\":3},{\"a\":\"1:3|2:4|3:2|4:2\",\"c\":1,\"i\":20003,\"ma\":\"1:3\",\"no\":3,\"set\":2},{\"a\":\"3:4|1:3|4:2|2:2\",\"c\":1,\"i\":20004,\"ma\":\"1:4\",\"no\":4,\"set\":1},{\"a\":\"1:3|4:3|5:2|3:3\",\"c\":1,\"i\":20005,\"ma\":\"1:5\",\"no\":5,\"set\":3},{\"a\":\"1:2|2:4|3:4|4:3\",\"c\":1,\"i\":20006,\"ma\":\"1:6\",\"no\":6,\"set\":1}]","roleId":36030446286411906,"size":0,"type":2},{"extData":"","id":36030446286411906,"packetData":"[]","roleId":36030446286411906,"size":0,"type":3}]

query3 table1
[{"chapterId":1,"dailyData":"","gold":285212672,"id":36030446286411906,"openData":"{\"id\":1,\"lv\":0}]\u0002[]\u0000\u0000\u0000\u0000\u0000:1,\"i\":20001,\"ma\":\"1:1\",\"no\":1,\"set\":3},{\"a\":\"3:4|5:2|1:4|4:2\",\"c\":","overData":",\"i\":20002,\"ma\":\"1:2\",\"no\":2,\"set\":3},{\"a\":\"1:3|2","roleId":36030446286411906,"status":863777850},{"chapterId":101,"dailyData":"","gold":352321536,"id":36030446286411906,"openData":"{\"id\":10101,\"lv\":0}]\u0002[]\u0000\u0000\u0000\u0000\u0000i\":20001,\"ma\":\"1:1\",\"no\":1,\"set\":3},{\"a\":\"3:4|5:2|1:4|4:2\",\"c\":","overData":",\"i\":20002,\"ma\":\"1:2\",\"no\":2,\"set\":3},{\"a\":\"1:3|2","roleId":36030446286411906,"status":863777850},{"chapterId":102,"dailyData":"","gold":352321536,"id":36030446286411906,"openData":"{\"id\":10201,\"lv\":0}]\u0002[]\u0000\u0000\u0000\u0000\u0000i\":20001,\"ma\":\"1:1\",\"no\":1,\"set\":3},{\"a\":\"3:4|5:2|1:4|4:2\",\"c\":","overData":",\"i\":20002,\"ma\":\"1:2\",\"no\":2,\"set\":3},{\"a\":\"1:3|2","roleId":36030446286411906,"status":863777850}]

**Comment by wangjing112** [comment] 2020-03-11 06:17
same 3 times querys from mysql return:
query1 table 1:
[{"chapterId":1,"gold":0,"id":36030446286411906,"openData":"[{\"id\":1,\"lv\":0}]","overData":"[]","roleId":36030446286411906,"status":0},{"chapterId":101,"gold":0,"id":36030446286411906,"openData":"[{\"id\":10101,\"lv\":0}]","overData":"[]","roleId":36030446286411906,"status":0},{"chapterId":102,"gold":0,"id":36030446286411906,"openData":"[{\"id\":10201,\"lv\":0}]","overData":"[]","roleId":36030446286411906,"status":0}]

query2 table 2:
[{"extData":"","id":36030446286411906,"packetData":"[{\"id\":10001,\"no\":1,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10002,\"no\":2,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":202},{\"args\":[],\"id\":301}]}},{\"id\":10003,\"no\":3,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":102},{\"args\":[],\"id\":201},{\"args\":[],\"id\":302}]}},{\"id\":10006,\"no\":4,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10007,\"no\":5,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10008,\"no\":6,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10009,\"no\":7,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10014,\"no\":8,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10015,\"no\":9,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10016,\"no\":10,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10017,\"no\":11,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10018,\"no\":12,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":10019,\"no\":13,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20001,\"no\":14,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20002,\"no\":15,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20003,\"no\":16,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20004,\"no\":17,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20005,\"no\":18,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20006,\"no\":19,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20007,\"no\":20,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20008,\"no\":21,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20009,\"no\":22,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20010,\"no\":23,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20011,\"no\":24,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20012,\"no\":25,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}},{\"id\":20013,\"no\":26,\"st\":1,\"talent\":{\"groups\":[{\"args\":[],\"id\":101},{\"args\":[],\"id\":201},{\"args\":[],\"id\":301}]}}]","roleId":36030446286411906,"size":0,"type":0},{"extData":"","id":36030446286411906,"packetData":"[{\"c\":10,\"i\":100},{\"c\":10,\"i\":101}]","roleId":36030446286411906,"size":0,"type":1},{"extData":"","id":36030446286411906,"packetData":"[{\"a\":\"2:2|4:4|3:2|5:2\",\"c\":1,\"i\":20001,\"ma\":\"1:1\",\"no\":1,\"set\":3},{\"a\":\"3:4|5:2|1:4|4:2\",\"c\":1,\"i\":20002,\"ma\":\"1:2\",\"no\":2,\"set\":3},{\"a\":\"1:3|2:4|3:2|4:2\",\"c\":1,\"i\":20003,\"ma\":\"1:3\",\"no\":3,\"set\":2},{\"a\":\"3:4|1:3|4:2|2:2\",\"c\":1,\"i\":20004,\"ma\":\"1:4\",\"no\":4,\"set\":1},{\"a\":\"1:3|4:3|5:2|3:3\",\"c\":1,\"i\":20005,\"ma\":\"1:5\",\"no\":5,\"set\":3},{\"a\":\"1:2|2:4|3:4|4:3\",\"c\":1,\"i\":20006,\"ma\":\"1:6\",\"no\":6,\"set\":1}]","roleId":36030446286411906,"size":0,"type":2},{"extData":"","id":36030446286411906,"packetData":"[]","roleId":36030446286411906,"size":0,"type":3}]

query3 table 1:
[{"chapterId":1,"gold":0,"id":36030446286411906,"openData":"[{\"id\":1,\"lv\":0}]","overData":"[]","roleId":36030446286411906,"status":0},{"chapterId":101,"gold":0,"id":36030446286411906,"openData":"[{\"id\":10101,\"lv\":0}]","overData":"[]","roleId":36030446286411906,"status":0},{"chapterId":102,"gold":0,"id":36030446286411906,"openData":"[{\"id\":10201,\"lv\":0}]","overData":"[]","roleId":36030446286411906,"status":0}]

**Comment by kimmking** [comment] 2020-03-11 06:38
The above infomation is not enough for profiling this issue. 
Can you make a simple demo to reproduce it?

**Comment by wangjing112** [comment] 2020-03-11 08:27
a query on 16:23 
in mysql this data is "[]" but now is wrong!
[image](https://user-images.githubusercontent.com/51982240/76396658-90091980-63b4-11ea-90a5-acd4390602ba.png)
is find in proxy log at 11:42 have a data like as:
![image](https://user-images.githubusercontent.com/51982240/76396708-a6af7080-63b4-11ea-9fe7-5620282e84e9.png)

**Comment by kimmking** [comment] 2020-03-11 14:19
Do you mean `@Column(length=2000)` lead to this issue?

**Comment by wangjing112** [comment] 2020-03-12 02:05
proxy log at error query 

2020-03-11 10:11:47,587 [ShardingSphere-Command-6] INFO [ShardingSphere-SQL] Rule Type: sharding
2020-03-11 10:11:47,587 [ShardingSphere-Command-6] INFO [ShardingSphere-SQL] Logic SQL: select stagechapt0_.chapterId as chapterId7_, stagechapt0_.roleId as roleId7_, stagechapt0_.dailyData as dailyData7_, stagechapt0_.extData as extData7_, stagechapt0_.gold as gold7_, stagechapt0_.openData as openData7_, stagechapt0_.overData as overData7_, stagechapt0_.status as status7_ from t_stage_info stagechapt0_ where stagechapt0_.roleId=?
2020-03-11 10:11:47,587 [ShardingSphere-Command-6] INFO [ShardingSphere-SQL] SQLStatement: SelectSQLStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@5822ceff, tablesContext=TablesContext(tables=[Table(name=t_stage_info, alias=Optional.of(stagechapt0_))], schema=Optional.absent())), projectionsContext=ProjectionsContext(startIndex=7, stopIndex=286, distinctRow=false, projections=[ColumnProjection(owner=stagechapt0_, name=chapterId, alias=Optional.of(chapterId7_)), ColumnProjection(owner=stagechapt0_, name=roleId, alias=Optional.of(roleId7_)), ColumnProjection(owner=stagechapt0_, name=dailyData, alias=Optional.of(dailyData7_)), ColumnProjection(owner=stagechapt0_, name=extData, alias=Optional.of(extData7_)), ColumnProjection(owner=stagechapt0_, name=gold, alias=Optional.of(gold7_)), ColumnProjection(owner=stagechapt0_, name=openData, alias=Optional.of(openData7_)), ColumnProjection(owner=stagechapt0_, name=overData, alias=Optional.of(overData7_)), ColumnProjection(owner=stagechapt0_, name=status, alias=Optional.of(status7_))], columnLabels=[chapterId7_, roleId7_, dailyData7_, extData7_, gold7_, openData7_, overData7_, status7_]), groupByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.groupby.GroupByContext@fa3ed2c, orderByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.orderby.OrderByContext@19f98287, paginationContext=org.apache.shardingsphere.sql.parser.relation.segment.select.pagination.PaginationContext@64338476, containsSubquery=false)
2020-03-11 10:11:47,587 [ShardingSphere-Command-6] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub0 ::: select stagechapt0_.chapterId as chapterId7_, stagechapt0_.roleId as roleId7_, stagechapt0_.dailyData as dailyData7_, stagechapt0_.extData as extData7_, stagechapt0_.gold as gold7_, stagechapt0_.openData as openData7_, stagechapt0_.overData as overData7_, stagechapt0_.status as status7_ from t_stage_info stagechapt0_ where stagechapt0_.roleId=? ::: [36029346774784530]

**Comment by tristaZero** [comment] 2020-03-17 05:03
Hi Thanks for your multiple feedback. 
After looking at your log info, I found there is no difference[1] between `logic SQL` and `actual SQL`,  which means sharding rule does not apply to this `logic table`. That's, it did not work well. 
Based on that, IMO it is better to double-check sharding rule and this SQL.
BTW, I did not dig out any exception from your log, is there any connection between the log and the title of this issue?

[1] Comparison
**Logic SQL**
> select stagechapt0_.chapterId as chapterId7_, stagechapt0_.roleId as roleId7_, stagechapt0_.dailyData as dailyData7_, stagechapt0_.extData as extData7_, stagechapt0_.gold as gold7_, stagechapt0_.openData as openData7_, stagechapt0_.overData as overData7_, stagechapt0_.status as status7_ from t_stage_info stagechapt0_ where stagechapt0_.roleId=?

**Actual SQL**
> select stagechapt0_.chapterId as chapterId7_, stagechapt0_.roleId as roleId7_, stagechapt0_.dailyData as dailyData7_, stagechapt0_.extData as extData7_, stagechapt0_.gold as gold7_, stagechapt0_.openData as openData7_, stagechapt0_.overData as overData7_, stagechapt0_.status as status7_ from t_stage_info stagechapt0_ where stagechapt0_.roleId=?

@wangjing112

**Comment by wangjing112** [comment] 2020-03-17 11:39
@tristaZero sql是没有错,但是返回的数据里面字符串发生了错误,字符串后面包含了其他不属于这个表的数据.
还有个重要的线索是,如果我用sql去查询是不会出差,比如:select * from table where id=123;
但是当我用org.hibernate.Session.get(Class arg0, Serializable arg1)去获取同样的数据,那么返回的数据就会出错.
你看我上面的截图,明显字符串后面出现你很久之前另外一个查询结果里面的字符串.

**Comment by tristaZero** [comment] 2020-03-19 02:47
@wangjiang112, Hi, Please Abide by the Apache community rule to involve in English.

**Comment by tristaZero** [comment] 2020-03-19 02:48
Is there any connection between the log you provided and the exception you faced.

**Comment by wangjing112** [comment] 2020-03-19 03:23
> Is there any connection between the log you provided and the exception you faced.


The point is no anly exception but result is wrong.
in mysql data type is varcher, when hibernate link proxy the result wrong like my picture.
but when use sharding-jdbc is work fine.

**Comment by tristaZero** [comment] 2020-03-20 04:04
You think the parameters of SQL got wrong, right? I want to make sure that the incorrect parameters you mentioned are which hibernate sent or proxy returned?

**Comment by wangjing112** [comment] 2020-03-20 06:29
> You think the parameters of SQL got wrong, right? I want to make sure that the incorrect parameters you mentioned are which hibernate sent or proxy returned?

hibernate->sharding-jdbc->mysql work fine
hibernate->proxool->mysql work fine
hibernate->proxool->sharding-proxy->mysql wrong

the wrong query use:Query org.hibernate.Query.setParameterList(String arg0, Collection arg1) throws
from hibernate-3.5.6

look this,16:23 progress B query result exist 11:42 progress A's Sql.
so i think the proxy process parameter query then result string out of buffer bounds.

> a query on 16:23
> in mysql this data is "[]" in table1 but now is wrong
> ![image](https://user-images.githubusercontent.com/51982240/76396658-90091980-63b4-11ea-90a5-acd4390602ba.png)
> is find in proxy log at 11:42 have a data like as:
> ![image](https://user-images.githubusercontent.com/51982240/76396708-a6af7080-63b4-11ea-9fe7-5620282e84e9.png)
> 
> even not a same table!

**Comment by tristaZero** [comment] 2020-03-22 02:17
Hi thanks for your explanation. 
> the wrong query use:Query org.hibernate.Query.setParameterList(String arg0, Collection arg1) from hibernate-3.5.6

This usage is not what we concerned since it will become a Query SQL sent to proxy finally. Therefore we need to get the `logic SQL` and `logic parameters` hibernate sends and `actual SQL` and `actual parameters` proxy rewrites. And then, we compare two of them to find the difference so as to figure out what proxy did.

**Comment by wangjing112** [comment] 2020-03-23 10:42
proxy log
`
2020-03-11 15:39:06,171 [ShardingSphere-Command-4] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub0 ::: select 1
2020-03-11 15:39:06,219 [ShardingSphere-Command-7] INFO [ShardingSphere-SQL] Rule Type: sharding
2020-03-11 15:39:06,219 [ShardingSphere-Command-7] INFO [ShardingSphere-SQL] Logic SQL: select stagechapt0_.chapterId as chapterId7_, stagechapt0_.roleId as roleId7_, stagechapt0_.dailyData as dailyData7_, stagechapt0_.extData as extData7_, stagechapt0_.gold as gold7_, stagechapt0_.openData as openData7_, stagechapt0_.overData as overData7_, stagechapt0_.status as status7_ from t_stage_info stagechapt0_ where stagechapt0_.roleId=?
2020-03-11 15:39:06,219 [ShardingSphere-Command-7] INFO [ShardingSphere-SQL] SQLStatement: SelectSQLStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@2b9dcdf7, tablesContext=TablesContext(tables=[Table(name=t_stage_info, alias=Optional.of(stagechapt0_))], schema=Optional.absent())), projectionsContext=ProjectionsContext(startIndex=7, stopIndex=286, distinctRow=false, projections=[ColumnProjection(owner=stagechapt0_, name=chapterId, alias=Optional.of(chapterId7_)), ColumnProjection(owner=stagechapt0_, name=roleId, alias=Optional.of(roleId7_)), ColumnProjection(owner=stagechapt0_, name=dailyData, alias=Optional.of(dailyData7_)), ColumnProjection(owner=stagechapt0_, name=extData, alias=Optional.of(extData7_)), ColumnProjection(owner=stagechapt0_, name=gold, alias=Optional.of(gold7_)), ColumnProjection(owner=stagechapt0_, name=openData, alias=Optional.of(openData7_)), ColumnProjection(owner=stagechapt0_, name=overData, alias=Optional.of(overData7_)), ColumnProjection(owner=stagechapt0_, name=status, alias=Optional.of(status7_))], columnLabels=[chapterId7_, roleId7_, dailyData7_, extData7_, gold7_, openData7_, overData7_, status7_]), groupByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.groupby.GroupByContext@53373328, orderByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.orderby.OrderByContext@4008634, paginationContext=org.apache.shardingsphere.sql.parser.relation.segment.select.pagination.PaginationContext@13e9876a, containsSubquery=false)
2020-03-11 15:39:06,219 [ShardingSphere-Command-7] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub0 ::: select stagechapt0_.chapterId as chapterId7_, stagechapt0_.roleId as roleId7_, stagechapt0_.dailyData as dailyData7_, stagechapt0_.extData as extData7_, stagechapt0_.gold as gold7_, stagechapt0_.openData as openData7_, stagechapt0_.overData as overData7_, stagechapt0_.status as status7_ from t_stage_info0 stagechapt0_ where stagechapt0_.roleId=? ::: [36030446286411906]
2020-03-11 15:39:06,251 [ShardingSphere-Command-11] INFO [ShardingSphere-SQL] Rule Type: sharding
2020-03-11 15:39:06,252 [ShardingSphere-Command-11] INFO [ShardingSphere-SQL] Logic SQL: SELECT @@session.tx_isolation
`

**Comment by wangjing112** [comment] 2020-03-23 10:45
find same wrong on other table.

**Comment by wangjing112** [comment] 2020-03-24 03:06
i found if the verchar data is "null" ,then string result possible have wrong value.

**Comment by wangjing112** [comment] 2020-03-24 03:56
a eg:
query by DBeaver ,data a=‘[{"id":1,"lv":0}]’ data b='[]'
![image](https://user-images.githubusercontent.com/51982240/77386197-3b5a9b00-6dc5-11ea-8fc7-9f0e2601667f.png)

in hibernate result return objects, data a='{"id":1,"lv":0}][]        '  and len=91,data b=''
![image](https://user-images.githubusercontent.com/51982240/77386415-b15f0200-6dc5-11ea-8098-3028fe225fe0.png)
see the string byte array ,no 16 is a '0'
![image](https://user-images.githubusercontent.com/51982240/77386497-e8351800-6dc5-11ea-8407-973cfcc11911.png)

**Comment by wangjing112** [comment] 2020-03-24 04:18
if i set not null value to the String data no1 and no2,then is get correct result.
![image](https://user-images.githubusercontent.com/51982240/77387871-85de1680-6dc9-11ea-8f68-f340da84e217.png)

**Comment by tristaZero** [comment] 2020-03-28 09:07
@wangjing112 You detailed investigation seems convinced. 
Could you provide us the Query SQL, parameters, and the configuration of the relevant query tables so that we can reproduce this exception in our local environment? You know, we need to do some debug. :)

**Comment by tristaZero** [comment] 2020-04-04 10:32
@wangjing112 Hi This issue is due, i.e., beyond seven days. I have to close it.
I am sorry it has no solution.

**Closed by tristaZero** 2020-04-04 10:32 UTC
