### ISSUE TITLE
7/5000   Distributed primary key issues

### ISSUE THREAD

**Issue by maomy** [apache/incubator-shardingsphere#1946] opened 2019-02-28 08:49 UTC
Does your distributed primary key use the default snowflake algorithm? Can you have a problem, encounter a problem in use process?

**Comment by terrymanu** [comment] 2019-02-28 10:42
What is your question?

**Comment by terrymanu** [comment] 2019-03-06 03:18
If no other update, I will close this issue tomorrow.

**Comment by terrymanu** [comment] 2019-03-07 04:32
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Closed by terrymanu** 2019-03-07 04:32 UTC
Labels: need feedback
