### ISSUE TITLE
Error when use "spring.jpa.hibernate.naming.physical-strategy"

### ISSUE THREAD

**Issue by softwbc** [apache/incubator-shardingsphere#2393] opened 2019-05-16 02:34 UTC
sharding-jdbc-spring-boot-starter 3.1.0
spring-boot-starter-parent 2.0.4.RELEASE

application.properties:
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

sharding.jdbc.config.sharding.tables.t_doc_process.actual-data-nodes.....

I want to map table names and fields with “..naming. physical-strategy”.
What can I do to get them to work together?
error:
java.lang.NullPointerException
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:126)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:42)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2933)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3524)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:637)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:282)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:263)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:317)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:783)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:768)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:305)
	at com.sun.proxy.$Proxy93.persist(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:490)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:377)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:629)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:593)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy98.save(Unknown Source)
	at org.xinhua.test.TestShardingSphere.testProcessSave2(TestShardingSphere.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by KomachiSion** [comment] 2019-05-16 04:26
Hi @softwbc, Could you provide your sharding configurations and steps to reproduce this problem?

**Comment by softwbc** [comment] 2019-05-16 08:42
####### application.properties #######
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
##hibernate 5.2.17.Final
##Java Model: private String cbOperationId; ==>Table field definition: `cbOperationId` 
##for field mapping
##MySQLSyntaxErrorException: Unknown column 'cb_operation_id' in 'field list'
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

sharding.jdbc.datasource.names=test
sharding.jdbc.datasource.test.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.test.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.test.url=jdbc:mysql://localhost/test?characterEncoding=utf8&useSSL=false
sharding.jdbc.datasource.test.username=root
sharding.jdbc.datasource.test.password=root

#sharding.jdbc.config.sharding.tables.t_doc_process.actual-data-nodes=test.t_doc_process_$->{0..9}
#sharding.jdbc.config.sharding.tables.t_doc_process.table-strategy.inline.sharding-column=docId
#sharding.jdbc.config.sharding.tables.t_doc_process.table-strategy.inline.algorithm-expression=test.t_doc_process_$->{docId % 10}

#others
sharding.jdbc.config.sharding.tables.my_friend.actual-data-nodes=test.my_friend_$->{0..9}
sharding.jdbc.config.sharding.tables.my_friend.table-strategy.inline.sharding-column=user_id
sharding.jdbc.config.sharding.tables.my_friend.table-strategy.inline.algorithm-expression=test.my_friend_$->{user_id % 10}


Once the physical-strategy configuration is used, the above null pointer exception occurs.

**Comment by softwbc** [comment] 2019-05-16 09:29
![qqqqqqqqqqqqqqqqqq](https://user-images.githubusercontent.com/8001444/57839667-b6dcda80-77f9-11e9-9b0e-7cfcb20196f2.jpg)

**Comment by KomachiSion** [comment] 2019-05-16 10:11
Sorry @softwbc, What's your entity and repo? I try to reproduce your problem.

**Comment by KomachiSion** [comment] 2019-05-20 01:34
@softwbc, I can't reproduce your problem, can you provide a example code and reproduce steps?
My example code is 

Entity:
```
@Setter
@Getter
@ToString
@Entity
@Table(name = "my_friend")
public class MyFriendEntity {
    
    @Id
    @Column
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    
    @Column
    private String status;
    
    @Column
    private int user_id;
}
```

Repo:
```
public interface MyFriendRepo extends JpaRepository<MyFriendEntity, Long> {
}
```

process:
```
        MyFriendRepo repo = applicationContext.getBean(MyFriendRepo.class);
        List<MyFriendEntity> list = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            MyFriendEntity myFriendEntity = new MyFriendEntity();
            myFriendEntity.setStatus("test");
            myFriendEntity.setUser_id((i % 5) + 100000);
            list.add(myFriendEntity);
        }
        repo.save(list);
```

configuration:
```
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
##hibernate 5.2.17.Final
##Java Model: private String cbOperationId; ==>Table field definition: cbOperationId
##for field mapping
##MySQLSyntaxErrorException: Unknown column 'cb_operation_id' in 'field list'
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

sharding.jdbc.datasource.names=test
sharding.jdbc.datasource.test.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.test.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.test.url=jdbc:mysql://localhost/demo_ds?characterEncoding=utf8&useSSL=false
sharding.jdbc.datasource.test.username=root
sharding.jdbc.datasource.test.password=

#sharding.jdbc.config.sharding.tables.t_doc_process.actual-data-nodes=test.t_doc_process_$->{0..9}
#sharding.jdbc.config.sharding.tables.t_doc_process.table-strategy.inline.sharding-column=docId
#sharding.jdbc.config.sharding.tables.t_doc_process.table-strategy.inline.algorithm-expression=test.t_doc_process_$->{docId % 10}

#others
sharding.jdbc.config.sharding.tables.my_friend.actual-data-nodes=test.my_friend_$->{0..9}
sharding.jdbc.config.sharding.tables.my_friend.key-generator-column-name=id
sharding.jdbc.config.sharding.tables.my_friend.table-strategy.inline.sharding-column=user_id
sharding.jdbc.config.sharding.tables.my_friend.table-strategy.inline.algorithm-expression=my_friend_$->{user_id % 10}

sharding.jdbc.config.props.sql.show=true
```

**Comment by softwbc** [comment] 2019-05-20 01:49
Hi, @KomachiSion 
Here is my test code
-- ----------------------------
-- Table structure for `t_doc_process_0`
-- ----------------------------
DROP TABLE IF EXISTS `t_doc_process_0`;
CREATE TABLE `t_doc_process_0` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `docId` char(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `docVersion` int(8) NOT NULL DEFAULT '0',
  `optUser` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `optUserId` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `optDept` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `optDeptId` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `optRole` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operationId` int(1) NOT NULL DEFAULT '0',
  `operationDateTime` datetime DEFAULT NULL,
  `operationInfo` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `createdBy` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedBy` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cbOperationId` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cbOperationName` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- DocProcess.java
-- ----------------------------
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;
@Entity
@Table(name = "t_doc_process")
public class DocProcess implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
//    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

//    @Column(name = "docId")
    private String docId;

//    @Column(name = "docVersion")
    private int docVersion;

//    @Column(name = "optUser")
    private String optUser;

//    @Column(name = "optUserId")
    private String optUserId;

//    @Column(name = "optDept")
    private String optDept;

//    @Column(name = "optDeptId")
    private String optDeptId;

//    @Column(name = "optRole")
    private String optRole;

//    @Column(name = "operationId")
    private Integer operationId;

//    @Column(name = "operationDateTime")
    private Date operationDateTime;

//    @Column(name = "operationInfo")
    private String operationInfo;

//    @Column(name = "createdBy")
    private String createdBy;

//    @Column(name = "created")
    private Date created;

//    @Column(name = "updatedBy")
    private String updatedBy;

//    @Column(name = "updated")
    private Date updated;

//    @Column(name = "cbOperationId")
    private String cbOperationId;

//    @Column(name = "cbOperationName")
    private String cbOperationName;

set and get......
}
-- ----------------------------
-- DocProcessRepository.java
-- ----------------------------
public interface DocProcessRepository extends JpaRepository<DocProcess,Long> {
}

-- ----------------------------
-- TestShardingSphere.java
-- ----------------------------
@RunWith(SpringRunner.class)
@SpringBootTest
public class TestShardingSphere {
    @Autowired
    private DocProcessRepository docProcessRepository;

    @Test
    public void testProcessSave2() throws IOException, SQLException, URISyntaxException {
        DocProcess docProcess = new DocProcess();
        set code......
        this.docProcessRepository.save(docProcess);
    }
}

**Comment by KomachiSion** [comment] 2019-05-20 02:04
@softwbc, I reproduce the problem and find the reason of the problem.

the sharding column `docId` is `String` type, but the sharding configuration is `{docId % 10}`. `String` type could not do `% operation` so the route failed.

you can use `t_doc_process_$->{docId.hashCode() % 10}` replace `test.t_doc_process_$->{docId % 10}` and retry, the problem can be solved.

**Comment by softwbc** [comment] 2019-05-20 07:38
@KomachiSion，Thanks
I see the reason for the problem. it works!

but，I've used custom algorithms to fragment.
table-strategy:
                    standard:
                      sharding-column: docId
                      precise-algorithm-class-name: xxxx

**Comment by KomachiSion** [comment] 2019-05-20 07:52
> @KomachiSion，Thanks
> I see the reason for the problem. it works!
> 
> but，I've used custom algorithms to fragment.
> table-strategy:
> standard:
> sharding-column: docId
> precise-algorithm-class-name: xxxx

it's ok.
If no other problem, can you close this issue?

**Closed** 2019-05-20 07:52 UTC
Labels: invalid

**Comment by softwbc** [comment] 2019-05-20 10:17
@KomachiSion Yes，thanks for your help！
