### ISSUE TITLE
sharding didn't affect when using sharding and encrypt!(4.0.0-RC2)

### ISSUE THREAD

**Issue by wm5723457** [apache/incubator-shardingsphere#2953] opened 2019-08-30 04:54 UTC
sharding is affected when encrypt。but query  is not decrypt. 
and I found The problem is (SQLServerResultSetMetaData)
`this.rs.getColumn(var1).getTableName().getObjectName();` ,this code return "",so cann't decrypt
for example config:
`encrypt:
      encryptors:
        encryptor_aes:
          type: aes
          props:
            aes.key.value: 123456
      tables:
        users:
          columns:
            mobile:
              cipherColumn: mobile_cipher
              encryptor: encryptor_aes
    props:
      query.with.cipher.column: true
      sql.show: true`

**Comment by sunbufu** [comment] 2019-08-31 01:26
Duplicate of https://github.com/apache/incubator-shardingsphere/issues/2924.

**Closed** 2019-08-31 15:07 UTC
Labels: duplicate
