### ISSUE TITLE
HeuristicMessage NoClassDefFoundError

### ISSUE THREAD

**Issue by mcdull6226** [apache/incubator-shardingsphere#1927] opened 2019-02-26 09:31 UTC
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shardingTransactionalAspect': Unsatisfied dependency expressed through method 'setEnvironment' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [io/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NoClassDefFoundError: com/atomikos/icatch/HeuristicMessage

sharding-transaction-2pc-xa 3.1.0
Running on docker java:8u111-jre

**Comment by cherrylzhao** [comment] 2019-02-26 12:47
hi，please tell more about your sharding-configuration from sharding-jdbc or proxy

**Comment by mcdull6226** [comment] 2019-02-27 03:02
3.0.0 runs normally, 3.1.0 cannot run on openjdk and 3.1.0 has this error on java:8 docker.

**Comment by cherrylzhao** [comment] 2019-02-27 04:43
is it ok in none-docker environment ? have you using XA transaction in your project?

**Comment by cherrylzhao** [comment] 2019-02-28 06:41
hi, please answer my question.

**Comment by cherrylzhao** [comment] 2019-03-04 04:24
hi, I have make a sharding-jdbc docker environment based our released example. the result is ok, so I think you have a wrong configuration while using XA transaction. so I will close this issue if you have no reply today.

**Comment by sfiloveyou** [comment] 2019-03-07 05:37
i have the same issue 
Caused by: java.lang.NoClassDefFoundError: com/atomikos/icatch/HeuristicMessage
	at io.shardingsphere.transaction.xa.manager.AtomikosDataSourceBeanWrapper.<init>(AtomikosDataSourceBeanWrapper.java:38) ~[sharding-transaction-2pc-xa-3.1.0.jar:na]
	at io.shardingsphere.transaction.xa.manager.AtomikosTransactionManager.wrapDataSource(AtomikosTransactionManager.java:106) ~[sharding-transaction-2pc-xa-3.1.0.jar:na]
	at io.shardingsphere.transaction.xa.convert.XADataSourceConverter.convert(XADataSourceConverter.java:54) ~[sharding-transaction-2pc-xa-3.1.0.jar:na]
	at io.shardingsphere.transaction.core.datasource.ShardingTransactionalDataSource.<init>(ShardingTransactionalDataSource.java:54) ~[sharding-transaction-core-3.1.0.jar:na]
	at io.shardingsphere.shardingjdbc.jdbc.adapter.AbstractDataSourceAdapter.<init>(AbstractDataSourceAdapter.java:59) ~[sharding-jdbc-core-3.1.0.jar:na]
	at io.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:54) ~[sharding-jdbc-core-3.1.0.jar:na]
	at io.shardingsphere.shardingjdbc.api.ShardingDataSourceFactory.createDataSource(ShardingDataSourceFactory.java:51) ~[sharding-jdbc-core-3.1.0.jar:na]
	at com.yiyunpower.yicloud.config.ShardingDruidDataSource.dataSource(ShardingDruidDataSource.java:117) ~[classes/:na]
	at com.yiyunpower.yicloud.config.ShardingDruidDataSource$$EnhancerBySpringCGLIB$$2339e312.CGLIB$dataSource$5(<generated>) ~[classes/:na]
	at com.yiyunpower.yicloud.config.ShardingDruidDataSource$$EnhancerBySpringCGLIB$$2339e312$$FastClassBySpringCGLIB$$134a4f11.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at com.yiyunpower.yicloud.config.ShardingDruidDataSource$$EnhancerBySpringCGLIB$$2339e312.dataSource(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_151]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	... 90 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.atomikos.icatch.HeuristicMessage
	at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_151]
	... 108 common frames omitted

**Comment by cherrylzhao** [comment] 2019-03-08 11:46
@sfiloveyou how can I reproduce your problem, would you please push your project to GitHub.

**Closed** 2019-03-14 04:37 UTC
Labels: need feedback

**Comment by terrymanu** [comment] 2019-03-18 15:34
**For English only**, other languages will not accept.

**Comment by terrymanu** [comment] 2019-03-18 15:34
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by xianlongbai** [comment] 2020-03-21 13:11
@Transactional
    public void testTrans() {
        TransactionTypeHolder.set(TransactionType.XA);
        for (int i = 0; i < 100; i++) {
            Order order = new Order();
            order.setOrderId((long)i+1);
            int number = new Random().nextInt(500) + 1;
            order.setUserId((long) number);
            if(i==50){
                throw new RuntimeException(" 模拟抛出一个异常！！！");
            }
            orderDao.saveToOne(order);
        }
    }

**Comment by xianlongbai** [comment] 2020-03-21 13:13
Caused by: java.lang.ClassNotFoundException: com.atomikos.icatch.HeuristicMessage

**Comment by xianlongbai** [comment] 2020-03-21 13:14
If you write as above, you will get such a wrong report
