### ISSUE TITLE
OutOfMemoryError caused by excessive pagination

### ISSUE THREAD

**Issue by jimmycheng888** [apache/incubator-shardingsphere#2774] opened 2019-07-27 06:19 UTC
### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
shardingsphere(Sharding-JDBC)
### Reason analyze (If you can)
I am using the postgresql database, I have adopted the strategy of sub-tables, my number of sub-tables is more than 200 tables, all the data amounts add up to 8000000, when I do a paged query and the OutOfMemoryError occurs for the last page, When I printed sql, I understood why, because the system sql rewrite function, changed the page, and then sorted the memory, but all of the tables queryed a large amount of data, resulting in exceeding my JVM settings. Memory, I have queried the official documentation, said that it is best to paginate each time, can index by ID, and then pagination, but my business scene is not allowed, because the customer will click on any page, which leads me to not follow Id index query, for example: select * from t_user limit 10 offset 50000, such sql will be rewritten as select * from t_user limit 50000 offset 0, I think this is a super serious bug, even if at any time should I want to click Any number of pages, and should not be paged according to the ID. My ID generation strategy is the snowflake algorithm, which is too destructive to the business and does not match. Business structure rules, hope to resolve as soon as possible

**Comment by terrymanu** [comment] 2019-07-27 14:34
Can you provide error message?

**Comment by jimmycheng888** [comment] 2019-07-28 07:17
> Can you provide error message?

Direct OutOfMemory, because when the number of pages turned over 8,000 pages, according to the information printed by the console, a table checked 80,000 records, resulting in java direct OutOfMemory, and then the situation is that many link link databases directly time out

**Comment by terrymanu** [comment] 2019-07-29 10:01
Please provide error message which your program reported.

**Comment by terrymanu** [comment] 2019-08-03 03:24
Will close soon if no response anymore.

**Comment by jimmycheng888** [comment] 2019-08-04 07:30
The extra logs are the same. I hope the author can solve this bug as soon as possible, because I think it is a few bugs that are easy to reproduce. I and my friends around me say that it is a bug in sharding-jdbc. In fact, mycat also has such a bug, the reason is also because of the sorting problem, please refer to https://blog.csdn.net/u013235478/article/details/53178657 for details.
However, I think there is a way to solve this problem. For example, first pass the total number of couns, then calculate the offset, and then rewrite sql. It can also solve the non-ID fragmentation, but sharding-jdbc does not. Provide such a function.

```
.....
2019-08-04 15:13:31.387 [http-nio-8210-exec-9] INFO  ShardingSphere-SQL - Actual SQL: user_1 ::: SELECT
        *
        FROM t_user_97 as u
        WHERE 1=1
        AND insert_time  >=?
         AND insert_time <=?
        ORDER BY id desc
            limit ? offset ? ::: [[2019-01-27T00:00:00.000+0800, 2019-08-04T23:59:59.000+0800, 852760, 0]]
2019-08-04 15:13:31.387 [http-nio-8210-exec-9] INFO  ShardingSphere-SQL - Actual SQL: user_1 ::: SELECT
        *
        FROM t_user_98 as u
        WHERE 1=1
        AND insert_time  >=?
         AND insert_time <=?
        ORDER BY id desc
            limit ? offset ? ::: [[2019-01-27T00:00:00.000+0800, 2019-08-04T23:59:59.000+0800, 852760, 0]]
2019-08-04 15:13:31.387 [http-nio-8210-exec-9] INFO  ShardingSphere-SQL - Actual SQL: user_1 ::: SELECT
       *
        WHERE 1=1
        AND insert_time  >=?
         AND insert_time <=?
        ORDER BY id desc
            limit ? offset ? ::: [[2019-01-27T00:00:00.000+0800, 2019-08-04T23:59:59.000+0800, 852760, 0]]
2019-08-04 15:13:31.387 [http-nio-8210-exec-9] INFO  ShardingSphere-SQL - Actual SQL: user_1 ::: SELECT
        *
        FROM t_user_100 as u
        WHERE 1=1
         AND insert_time  >=?
         AND insert_time <=?
        ORDER BY id desc
            limit ? offset ? ::: [[2019-01-27T00:00:00.000+0800, 2019-08-04T23:59:59.000+0800, 852760, 0]]
Exception in thread "http-nio-8210-ClientPoller-1" Exception in thread "NettyClientWorkerThread_2" Exception in thread "recoverScheduler_QuartzSchedulerThread" Exception in thread "AsyncAppender-Dispatcher-Thread-25" Exception in thread "MQ-AsyncTraceDispatcher-Thread-be9e7518-bf87-4d9b-93f7-a42668e86cfc" Exception in thread "Catalina-utility-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by tuohai666** [comment] 2019-08-05 07:36
I don't know the implementation of MyCat, but I think ShardingSphere don't have the problem.

ShardingSphere provide ways to save memory. Please follow the instructions below to reduce the memory cost.

1. Make a stream ResultSet:
**statement.setFetchSize(1);** 
or
jdbc:postgresql://127.0.0.1:5432/demo?**defaultRowFetchSize=1**

2. Make sure the ExecuteEngine in MEMORY_STRICTLY Mode:
I noticed your SQL will be full routed to 200 nodes. (Everyone need to avoid full routing)
Any way, set the props max.connections.size.per.query more than 200. For example:
**max.connections.size.per.query: 300**

After 1&2, both jdbc and ShardingSphere will not fetch all data in memory.

For more details: 
https://mp.weixin.qq.com/s?__biz=MzUzNjgwODk2Mw==&mid=2247483679&idx=1&sn=ee7335b72b9105a53a55ee59b42358b1&chksm=faf1da73cd8653656b0c56ba852a98d67eb67f4f36e294a8c08507f5c3dc3b6897a90b99ea53&scene=0&key=4062b15c04f483fc1db8d4359b898767266e0bca63e1553ea724f2bf8a298d9cb0562f695b0804411c278e9e3db279cf63de75965c6f84781027c9ab8495334243939bbfc2f8ee21bacda90671addb29&ascene=1&uin=MTM1ODcxNDE1&devicetype=Windows+7&version=62060833&lang=zh_CN&pass_ticket=CdqzKWxf9iryvwQkRSxKqGt8Wz3LIqnQyhtmzMOC6eY%3D

**Comment by jimmycheng888** [comment] 2019-08-06 03:42
> I don't know the implementation of MyCat, but I think ShardingSphere don't have the problem.
> 
> ShardingSphere provide ways to save memory. Please follow the instructions below to reduce the memory cost.
> 
> 1. Make a stream ResultSet:
>    **statement.setFetchSize(1);**
>    or
>    jdbc:postgresql://127.0.0.1:5432/demo?**defaultRowFetchSize=1**
> 2. Make sure the ExecuteEngine in MEMORY_STRICTLY Mode:
>    I noticed your SQL will be full routed to 200 nodes. (Everyone need to avoid full routing)
>    Any way, set the props max.connections.size.per.query more than 200. For example:
>    **max.connections.size.per.query: 300**
> 
> After 1&2, both jdbc and ShardingSphere will not fetch all data in memory.
> 
> For more details:
> https://mp.weixin.qq.com/s?__biz=MzUzNjgwODk2Mw==&mid=2247483679&idx=1&sn=ee7335b72b9105a53a55ee59b42358b1&chksm=faf1da73cd8653656b0c56ba852a98d67eb67f4f36e294a8c08507f5c3dc3b6897a90b99ea53&scene=0&key=4062b15c04f483fc1db8d4359b898767266e0bca63e1553ea724f2bf8a298d9cb0562f695b0804411c278e9e3db279cf63de75965c6f84781027c9ab8495334243939bbfc2f8ee21bacda90671addb29&ascene=1&uin=MTM1ODcxNDE1&devicetype=Windows+7&version=62060833&lang=zh_CN&pass_ticket=CdqzKWxf9iryvwQkRSxKqGt8Wz3LIqnQyhtmzMOC6eY%3D

1. In fact, mycat also has this problem, the official is also recommended to use id query and then pagination, it is not recommended to directly page.
2.Sharding-Proxy does not support postgresql
3. Some more complicated queries, I think ShardingSphere has more advantages, because some queries I need to use stored procedures, I have written a set of business rules tool class, can directly get the specified data source directly from ShardingDataSource and then execute through JdbcTemplate .
4. The answer you provided is not the same question that I am asking. The question I asked is ShardingSphere page sorting. Because the memory is too large, the memory leaks, and you send a ShardingSphere principle and optimization process.
5. I have doubted whether the mqsql driver and the postgresql driver are inconsistent. It may be that mysql does not get all the data at once, and the postgresql driver may acquire all the data at a time, and then perform the memory and return, which leads to a one-time query. 8000000 data out of memory caused memory overflow, I tried to increase the java memory, and then did not crash, but when returned, the query is super slow, I spent more than 8 seconds from the beginning to the end of the data query, this is unacceptable If multiple concurrent calls will cause the same problem, memory overflows.
6. Actually, I have thought about the solution.
     First, it is preloading a number of data and then paging according to id.
     Second, or synchronize the data to mongodb or ElasticSearch, but postgresql is not the same as mysql, can not directly resolve binlog, and the server is Alibaba Cloud, if using mq as compensation and frequently update the table data, resulting in business is extremely complicated , but also involves the order before and after, if the use of sequential messages involves the issue of fast consumption, of course, I can specify the channel.

**Comment by tuohai666** [comment] 2019-08-06 03:57
Maybe you don't understand. Just follow the instructions. And feedback whether there's still "memory leak". 

1. Make a stream ResultSet:
**statement.setFetchSize(1);** 
or
jdbc:postgresql://127.0.0.1:5432/demo?**defaultRowFetchSize=1**

2. Make sure the ExecuteEngine in MEMORY_STRICTLY Mode:
I noticed your SQL will be full routed to 200 nodes. (Everyone need to avoid full routing)
Any way, set the props max.connections.size.per.query more than 200. For example:
**max.connections.size.per.query: 300**

**Comment by jimmycheng888** [comment] 2019-08-06 03:58
> Maybe you don't understand. Just follow the instructions. And feedback whether there's still "memory leak".
> 
> 1. Make a stream ResultSet:
>    **statement.setFetchSize(1);**
>    or
>    jdbc:postgresql://127.0.0.1:5432/demo?**defaultRowFetchSize=1**
> 2. Make sure the ExecuteEngine in MEMORY_STRICTLY Mode:
>    I noticed your SQL will be full routed to 200 nodes. (Everyone need to avoid full routing)
>    Any way, set the props max.connections.size.per.query more than 200. For example:
>    **max.connections.size.per.query: 300**

I have tried your configuration above, but this time it is a lot better, the system does not crash, but because the processing time is too long, the database timeout, if a large number of links, will drag the database. The error message is as follows:

`java.sql.SQLTransientConnectionException: HikariPool-3 - Connection is not available, request timed out after 30000ms.`

**Comment by tuohai666** [comment] 2019-08-06 04:00
I suppose there are 200 connections to MySQL. So please check the max connections of HikariCP and MySQL server.

**Comment by jimmycheng888** [comment] 2019-08-06 05:07
> I suppose there are 200 connections to MySQL. So please check the max connections of HikariCP and MySQL server. Both of them must more than 200.

Not the larger the number of database connections, the better the database has a limit on the number of connections. Generally speaking, postgresql exceeds 800 for obvious performance problems. Plus, our service is distributed cluster, and a service if it is behind 200 As you can imagine, I think this is a solution that cannot solve the problem. You can refer to the following article:
https://www.jianshu.com/p/a8f653fc0c54
https://blog.csdn.net/X5fnncxzq4/article/details/80649679

**Comment by tuohai666** [comment] 2019-08-06 06:41
Maybe you don't understand. Why not follow the instructions. And feedback whether there's still SQLTransientConnectionException.

I suppose there are x connections to MySQL. So please check the max connections of HikariCP and MySQL server. Both of them must more than x.

**Comment by jimmycheng888** [comment] 2019-08-06 07:45
> Maybe you don't understand. Why not follow the instructions. And feedback whether there's still SQLTransientConnectionException.
> 
> I suppose there are x connections to PostgreSQL. So please check the max connections of HikariCP and PostgreSQL server. Both of them must more than x.

I just set the property to max.connections.size.per.query: 5, or there is a memory leak, defaultRowFetchSize=1 is also set.

**Comment by tuohai666** [comment] 2019-08-06 07:52
Tell me how many connections will be created by the full routing? Or directly show me the shardingRule and datasources. Let's suppose the number is x to save time.

I suppose there are x connections to PostgreSQL. So please check the max connections of HikariCP and PostgreSQL server. Both of them must more than x.

**Comment by jimmycheng888** [comment] 2019-08-06 08:11
> Tell me how many connections will be created by the full routing? Or directly show me the shardingRule and datasources. Let's suppose the number is x to save time.
> 
> I suppose there are x connections to PostgreSQL. So please check the max connections of HikariCP and PostgreSQL server. Both of them must more than x.

sharding:
  jdbc:
    dataSource:
      names: user-master-01,user-1-slave-0,user-1-slave-1,user-master-02,user-2-slave-0,user-2-slave-1,user-master-03,user-3-slave-0,user-3-slave-1,user-master-04,user-4-slave-0,user-4-slave-1,user-master-05,user-5-slave-0,user-5-slave-1
      user-master-01:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5800/user_01?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: false 
        connection-timeout: 30000 
        idle-timeout: 30000 
        max-lifetime: 180000 
        maximum-pool-size: 10 
        minimum-idle: 3 
        auto-commit: true 
        connection-test-query: SELECT 'x'
      user-1-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5801/user_01?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
      user-1-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5802/user_01?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
      user-master-02:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5800/user_02?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: false
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        auto-commit: true
        connection-test-query: SELECT 'x'
      user-2-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5801/user_02?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
      user-2-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5802/user_02?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
      user-master-03:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5800/user_03?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: false
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        auto-commit: true
        connection-test-query: SELECT 'x'
      user-3-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5801/user_03?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
      user-3-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5802/user_03?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
      user-master-04:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5800/user_04?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: false
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        auto-commit: true
        connection-test-query: SELECT 'x'
      user-4-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5801/user_04?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
      user-4-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5802/user_04?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
      user-master-05:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5800/user_05?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: false
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        auto-commit: true
        connection-test-query: SELECT 'x'
      user-5-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5801/user_05?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
      user-5-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://127.0.0.1:5802/user_05?defaultRowFetchSize=1
        username: postgres
        password: myPassword
        read-only: true
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 180000
        maximum-pool-size: 10
        minimum-idle: 3
        connection-test-query: SELECT 'x'
    config:
      sharding:
        tables:
          t_user:
            actualDataNodes: user_${1..5}.t_user_${1..100}
            tableStrategy:
              standard:
                sharding-column: user_id
                precise-algorithm-class-name: com.AlgorithmSharding
        masterSlaveRules:
          user_1:
            masterDataSourceName: user-master-01
            slaveDataSourceNames: [user-1-slave-0, user-1-slave-1]
            loadBalanceAlgorithmType: RANDOM
          user_2:
            masterDataSourceName: user-master-02
            slaveDataSourceNames: [user-2-slave-0, user-2-slave-1]
            loadBalanceAlgorithmType: RANDOM
          user_3:
            masterDataSourceName: user-master-03
            slaveDataSourceNames: [user-3-slave-0, user-3-slave-1]
            loadBalanceAlgorithmType: RANDOM
          user_4:
            masterDataSourceName: user-master-04
            slaveDataSourceNames: [user-4-slave-0, user-4-slave-1]
            loadBalanceAlgorithmType: RANDOM
          user_5:
            masterDataSourceName: user-master-05
            slaveDataSourceNames: [user-5-slave-0, user-5-slave-1]
            loadBalanceAlgorithmType: RANDOM
      props:
        sql.show: true
        max.connections.size.per.query: 5
reproduce this problem, you can set the java startup parameters as follow

`-Xmx128m -Xms64m -XX:+HeapDumpOnOutOfMemoryError -X:HeapDumpPath=E:\heap_dump.log`

**Comment by tuohai666** [comment] 2019-08-06 08:43
5 databases * 100 tables = 500 connections per PostgreSQL instance.

For HikariCP:
maximum-pool-size: 110

For ShardingSphere:
max.connections.size.per.query: 110

For PostgreSQL Server:
max_connections = 600

You know, follow the instructions.

**Comment by jimmycheng888** [comment] 2019-08-07 03:20
> 5 databases * 100 tables = 500 connections per PostgreSQL instance.
> 
> For HikariCP:
> maximum-pool-size: 110
> 
> For ShardingSphere:
> max.connections.size.per.query: 110
> 
> For PostgreSQL Server:
> max_connections = 600
> 
> You know, follow the instructions.


Still the memory overflows, there is no fundamental problem
```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to E:\heap_dump.log ...
Unable to create E:\heap_dump.log: File exists
```

**Comment by tuohai666** [comment] 2019-08-07 03:47
So, there's no SQLTransientConnectionException?
If out of memory this time, it means you will occur out of memory connecting database without sharding-jdbc. If not, it is because you didn't follow my constructions completely.

We don't talk about how many connections is right for now. You can choose less memory cost or less connections cost, but you can't choose both of them. Full routing is not the correct design, if you insist full routing, you have to trade off.

**Comment by jimmycheng888** [comment] 2019-08-07 04:57
> So, there's no SQLTransientConnectionException?
> If out of memory this time, it means you will occur out of memory connecting database without sharding-jdbc. If not, it is because you didn't follow my constructions completely.
> 
> We don't talk about how many connections is right for now. You can choose less memory cost or less connections cost, but you can't choose both of them. Full routing is not the correct design, if you insist full routing, you have to trade off.

I have completely followed your configuration, I set it up.
For HikariCP:
Maximum-pool-size: 110

For ShardingSphere:
Max.connections.size.per.query: 110

For PostgreSQL Server:
Max_connections = 600
But still memory overflow, full routing can not be avoided, because it is in the background management page query information, business requirements are not allowed to specify the route, and more than 100 tables, completely routing according to the user id, can not always check according to the user For example, I want to query all users of my system, and on page 8000, because I don't remember my user name, I only remember him on the previous page of the last page, of course you can say the minimum id Query it, then check it later, but if I want to check half of it at this time? This is the customer's needs, and the system is also designed according to the business.

**Comment by tuohai666** [comment] 2019-08-07 05:07
Have you missed my question? "So, there's no SQLTransientConnectionException?"
Have you got the point of "If out of memory this time, it means you will occur out of memory connecting database without sharding-jdbc."?

**Comment by jimmycheng888** [comment] 2019-08-07 09:07
> Have you missed my question? "So, there's no SQLTransientConnectionException?"
> Have you got the point of "If out of memory this time, it means you will occur out of memory connecting database without sharding-jdbc."?

The program does not throw a SQLTransientConnectionException, but directly OutOfMemoryError, I am sure that when I query the unfragmented table, I did not throw OutOfMemoryError, and I will not appear OutOfMemoryError when querying the first page, even the first few hundred pages of data. , but throw OutOfMemoryError if you directly page to 899999 pages

**Comment by tuohai666** [comment] 2019-08-07 09:21
There's only one row in the memory per ResultSet at a time since you set **defaultRowFetchSize=1**.
One row can't lead to an OutOfMemoryError. Please analyze what's in the memory.

**Comment by tuohai666** [comment] 2019-08-07 09:23
In case of misunderstanding, show me the current shardingRule and datasources.

**Comment by tuohai666** [comment] 2019-08-07 10:10
Here are some new findings.

For MySQL statement.setFetchSize() is enough to make a stream ResultSet. 
But for PostgreSQL there's another condition(I missed before) to make the ResultSet stream. After I checked the document, I found the condition:
**conn.setAutoCommit(false);**

I believe the OutOfMemoryError is caused by the lack of this condition, so please modify your code and try again.

Make a stream ResultSet:
1. **statement.setFetchSize(1);**
    or
    jdbc:postgresql://127.0.0.1:5432/demo?**defaultRowFetchSize=1**
2. **conn.setAutoCommit(false);**

You can find the example code for turn on/off stream ResultSet via PostgreSQL document: 
https://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor

**Comment by jimmycheng888** [comment] 2019-08-07 10:19
> Here are some new findings.
> 
> For MySQL statement.setFetchSize() is enough to make a stream ResultSet.
> But for PostgreSQL there's another condition(I missed before) to make the ResultSet stream. After I checked the document, I found the condition:
> **conn.setAutoCommit(false);**
> 
> I believe the OutOfMemoryError is caused by the lack of this condition, so please modify your code and try again.
> 
> Make a stream ResultSet:
> 
> 1. **statement.setFetchSize(1);**
>    or
>    jdbc:postgresql://127.0.0.1:5432/demo?**defaultRowFetchSize=1**
> 2. **conn.setAutoCommit(false);**
> 
> You can find the example code for turn on/off stream ResultSet via PostgreSQL document:
> https://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor

error logs:
```
"ShardingSphere-313" daemon prio=5 tid=475 RUNNABLE
	at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:48)
	at org.postgresql.core.PGStream.receiveTupleV3(PGStream.java:421)
	   Local Variable: byte[][]#31850
	   Local Variable: org.postgresql.core.PGStream#443
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2146)
	   Local Variable: java.util.ArrayList#29306
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	   Local Variable: org.postgresql.core.v3.QueryExecutorImpl#443
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	   Local Variable: org.postgresql.core.v3.SimpleQuery#3659
	   Local Variable: org.postgresql.jdbc.PgStatement$StatementResultHandler#260
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	   Local Variable: org.postgresql.core.CachedQuery#404
	   Local Variable: org.postgresql.core.v3.SimpleParameterList#401
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	   Local Variable: org.postgresql.jdbc.PgPreparedStatement#399
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	   Local Variable: com.zaxxer.hikari.pool.HikariProxyPreparedStatement#377
	at io.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$2.executeSQL(SQLExecuteCallbackFactory.java:63)
	at io.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$2.executeSQL(SQLExecuteCallbackFactory.java:59)
	at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:72)
	   Local Variable: io.shardingsphere.spi.executor.SPISQLExecutionHook#261
	   Local Variable: io.shardingsphere.core.metadata.datasource.dialect.PostgreSQLDataSourceMetaData#261
	at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:61)
	   Local Variable: java.util.LinkedList#7812
	   Local Variable: io.shardingsphere.core.executor.StatementExecuteUnit#377
	   Local Variable: java.util.LinkedList$ListItr#263
	   Local Variable: java.util.LinkedList#712
	at io.shardingsphere.core.executor.ShardingExecuteEngine$2.call(ShardingExecuteEngine.java:169)
	at io.shardingsphere.core.executor.ShardingExecuteEngine$2.call(ShardingExecuteEngine.java:165)
	   Local Variable: io.shardingsphere.core.executor.ShardingExecuteEngine$2#262
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	   Local Variable: com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask#262
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	   Local Variable: com.google.common.util.concurrent.TrustedListenableFutureTask#315
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	   Local Variable: java.util.concurrent.ThreadPoolExecutor$Worker#310
	at java.lang.Thread.run(Thread.java:745)

```
I am using spring boot + mybatis transaction is controlled by spring, you can not directly use these parameters, it will destroy the original structure of my code, if you can fix this bug, I hope that the next version of shardingsphere can be fixed, because Almost no project now uses jdbc as the most basic database operation. It is based on third-party tools such as mybatis, hibernate, JPA... Have you tested it locally?

**Comment by tuohai666** [comment] 2019-08-07 10:44
If you don't want to make progress, this issue should be at the end.
We provide ways which are precise and operational to resolve your problem. But "how to change the parameter in Spring", you can study by yourself or turn to others for help.
Please note this issue is not a bug. It's not the timing to discuss whether it's a bug or not, because you are not ready yet.

**Comment by terrymanu** [comment] 2019-08-13 10:36
Can we close this issue?

**Closed** 2019-08-16 03:09 UTC
Labels: need feedback

**Comment by jimmycheng888** [comment] 2019-08-16 11:36
https://github.com/apache/incubator-shardingsphere/issues/2774#issuecomment-520782523
