### ISSUE TITLE
sharding-jdbc-spring-namespace 4.0.0-RC1 namespcae configuration

### ISSUE THREAD

**Issue by jiejiecool** [apache/incubator-shardingsphere#2052] opened 2019-03-18 12:33 UTC
**## because concurrent problem in on-line environment, so i downloaded 4.0.0-RC1 version and package it .But i'm getting in trouble when startup. This is my namespace configuration, but when startup,the error below occured, like this**

`<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:sharding="http://shardingsphere.apache.org/schema/shardingsphere/sharding" xsi:schemaLocation="
        http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://shardingsphere.apache.org/schema/shardingsphere/sharding
        http://shardingsphere.apache.org/schema/shardingsphere/sharding/sharding.xsd">`

`Caused by: org.xml.sax.SAXParseException: TargetNamespace.1: 应为名称空间 'http://shardingsphere.apache.org/schema/shardingsphere/sharding', 但方案文档的目标名称空间为 'http://shardingsphere.io/schema/shardingsphere/sharding'。`

I guess the problem is 
`http://shardingsphere.apache.org/schema/shardingsphere/sharding/sharding.xsd`
but targetNameSpace in this xsd file is
`<xsd:schema xmlns="http://shardingsphere.io/schema/shardingsphere/sharding"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:beans="http://www.springframework.org/schema/beans"
            targetNamespace="http://shardingsphere.io/schema/shardingsphere/sharding"`

**Comment by KomachiSion** [comment] 2019-03-19 01:03
@jiejiecool I have checked the xsd file, but I don't find this problem, would you mind inform which branch you download?
Or provide more detail information about the xsd and pom file about ShardingSphere.

**Comment by jiejiecool** [comment] 2019-03-19 02:56
I used TAG 4.0.0-RC1,  packaged and deployed source code as a jar to personal maven repository,but I found tag-4.0.0-RC1 was deleted.

**Comment by KomachiSion** [comment] 2019-03-19 03:07
Sorry for the confusion, can you clone the **dev** branch and install in your local environment, then try to reproduce this problem with 4.0.0-RC1-SNAPSHOT? Because I cannot reproduce this problem.

**Comment by abbbud** [comment] 2019-03-19 10:07
same exception, need help

**Comment by KomachiSion** [comment] 2019-03-19 12:04
@abbbud Are you using `TAG 4.0.0-RC1`? Or `4.0.0-RC1-SNAPSHOT`?

**Comment by abbbud** [comment] 2019-03-20 01:52
@KomachiSion NO,I USE TAG 3.1.0

**Comment by KomachiSion** [comment] 2019-03-20 02:18
@abbbud 3.1.0 is not apache release. it should be `http://shardingsphere.io/schema/shardingsphere/sharding`. Maybe your configuration file has some error, I suggest you open a new issue and provide describe your situation and configuration.

**Comment by KomachiSion** [comment] 2019-03-21 00:56
@jiejiecool Can you reproduce this problem with `4.0.0-RC1-SNAPSHOT` version?

**Comment by KomachiSion** [comment] 2019-03-26 01:09
It should be caused by old xsd files in the official website.

**Comment by KomachiSion** [comment] 2019-03-26 01:25
refer [apache/incubator-shardingsphere-doc#109](https://github.com/apache/incubator-shardingsphere-doc/issues/109)

**Comment by KomachiSion** [comment] 2019-03-27 06:49
Fixed by [apache/incubator-shardingsphere-doc#109](https://github.com/apache/incubator-shardingsphere-doc/issues/109)

**Closed** 2019-03-27 06:49 UTC
Labels: bug
