### ISSUE TITLE
The sharding-JDBC non-sharding policy, NoneShardingStrategy, does not work in yml

### ISSUE THREAD

**Issue by devefx** [apache/incubator-shardingsphere#3977] opened 2020-01-14 13:23 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

4.0.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Expected behavior

```yml
my_table:
  database-strategy:
    none:
      any: 1
```

```java
public class YamlShardingStrategyConfiguration implements YamlConfiguration {
    
    private YamlStandardShardingStrategyConfiguration standard;
    
    private YamlComplexShardingStrategyConfiguration complex;
    
    private YamlHintShardingStrategyConfiguration hint;
    
    private YamlInlineShardingStrategyConfiguration inline;
    
    private YamlNoneShardingStrategyConfiguration none; // no null
}
```

### Actual behavior

```java
public class YamlShardingStrategyConfiguration implements YamlConfiguration {
    
    private YamlStandardShardingStrategyConfiguration standard;
    
    private YamlComplexShardingStrategyConfiguration complex;
    
    private YamlHintShardingStrategyConfiguration hint;
    
    private YamlInlineShardingStrategyConfiguration inline;
    
    private YamlNoneShardingStrategyConfiguration none; // is null
}
```

### Reason analyze (If you can)

`org.apache.shardingsphere.core.yaml.config.sharding.strategy.YamlNoneShardingStrategyConfiguration`  There must be a field, like `private boolean enabled;`

```yml
my_table:
  database-strategy:
    none:
      enabled: true
```

**Comment by KomachiSion** [comment] 2020-01-15 04:57
Why do you set sub configure for none strategy?

**Comment by KomachiSion** [comment] 2020-01-15 08:14
@devefx Can you try to use? 
```yaml
my_table:
  database-strategy:
    none: {}
```

**Comment by devefx** [comment] 2020-01-15 12:14
> @devefx Can you try to use?
> 
> ```yaml
> my_table:
>   database-strategy:
>     none: {}
> ```

Still not working, a field must be included

**Comment by KomachiSion** [comment] 2020-01-15 12:20
For my test,

```yaml
my_table:
  database-strategy:
    none: {}
```

This configuration can work. 

Can you provide your full sharding configuration? Or example code?

**Comment by devefx** [comment] 2020-01-15 12:23
![image](https://user-images.githubusercontent.com/15070360/72433673-d71fc780-37d4-11ea-8ded-29d2b987ea71.png)

**Comment by KomachiSion** [comment] 2020-01-15 12:28
Sorry, picture is not full configuration and quite inconvenient.
Please paste congfiguration as a text to comment.
You can remove some important data like username,password,url and so on.

**Comment by devefx** [comment] 2020-01-15 12:28
![image](https://user-images.githubusercontent.com/15070360/72433886-4b5a6b00-37d5-11ea-809f-d2b055a70875.png)

```java
package org.apache.shardingsphere.core.yaml.config.sharding.strategy;

import lombok.Data;

@Data
public final class YamlNoneShardingStrategyConfiguration implements YamlBaseShardingStrategyConfiguration {

    private boolean enabled;
}
```
This is me override

**Comment by devefx** [comment] 2020-01-15 12:31
This my configuration

```yml
  shardingsphere:
    datasource:
      names: default, marketdata
      default:
        xxxx
      marketdata:
        xxx
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: default
      default-database-strategy:
        standard:
          sharding-column: uid
          precise-algorithm-class-name: my.shardingsphere.strategy.DatabasePreciseShardingAlgorithm
      default-table-strategy:
        standard:
          sharding-column: uid
          precise-algorithm-class-name: my.shardingsphere.strategy.TablePreciseShardingAlgorithm
      tables:
        price_index:
          actual-data-nodes: marketdata.price_index
          database-strategy:
            none: {}
          table-strategy:
            none: {}

```

**Comment by KomachiSion** [comment] 2020-01-16 07:06
I find the problem is caused by springboot. 
springboot parse yaml and transfer to propertySource. At this time, springboot would ignore some item.

I'm not sure whether there are some configuration so that springboot do not ignore them.

**Comment by devefx** [comment] 2020-01-16 07:13
Add a field? like `private boolean enabled;`

**Comment by KomachiSion** [comment] 2020-01-16 07:16
> Add a field? like `private boolean enabled;`

Not a good idea, the NoneStrategy already means do nothing. If set a sub field `enabled`, Is it means a true switch when `enabled=true`? I think it will confuse users.

**Comment by KomachiSion** [comment] 2020-01-17 06:56
I will close this issue because create and describe in new issue#4005.

If has more discussion or solution, please move to #4005.

**Closed by KomachiSion** 2020-01-17 06:56 UTC
Labels: question

**Comment by sui6666666** [comment] 2024-04-12 06:57
> I find the problem is caused by springboot. springboot parse yaml and transfer to propertySource. At this time, springboot would ignore some item.
> 
> I'm not sure whether there are some configuration so that springboot do not ignore them.

I have the same problem ,and i am useing sharding-jdbc 5.2.1

**Comment by yorickopennet** [comment] 2024-10-03 13:53
same on sharding-jdbc 5.5.0
