### ISSUE TITLE
Sharding-proxy master-slave in sharding doesn't work

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2782] opened 2019-07-29 09:57 UTC
I have configed master-slave separation in sharding, but actually when i take select operation it wasn't routed to slave node? why ? Here is my sharding configurations for your referance, any comments ?
**datasource:**
neworiental_answer: !!io.shardingsphere.orchestration.yaml.YamlDataSourceConfiguration
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  properties:
    maxPoolSize: 50
    maintenanceIntervalMilliseconds: 30000
    url: jdbc:mysql://192.168.0.10:33060/neworiental_answer?serverTimezone=UTC&useSSL=false
    minPoolSize: 1
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    connectionTimeoutMilliseconds: 30000
    password: qq9527@xdf
    username: admin
slave_answer_0: !!io.shardingsphere.orchestration.yaml.YamlDataSourceConfiguration
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  properties:
    maxPoolSize: 50
    maintenanceIntervalMilliseconds: 30000
    url: jdbc:mysql://192.168.0.11:44060/neworiental_answer?serverTimezone=UTC&useSSL=false
    minPoolSize: 1
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 0
    connectionTimeoutMilliseconds: 30000
    password: 1a2s3dqwe
    username: reader

**rule:**
bindingTables:
- entity_stu_ques_knowledge,entity_student_error_exe,entity_student_exercise,cms_brush_questions_correct
defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
masterSlaveRules:
  ms_answer:
    loadBalanceAlgorithmClassName: io.shardingsphere.api.algorithm.masterslave.RoundRobinMasterSlaveLoadBalanceAlgorithm
    masterDataSourceName: neworiental_answer
    name: ms_answer
    slaveDataSourceNames:
    - slave_answer_0
tables:
  entity_stu_ques_knowledge:
    actualDataNodes: ms_answer.entity_stu_ques_knowledge_${0..99}
    keyGeneratorColumnName: id
    logicTable: entity_stu_ques_knowledge
    tableStrategy:
      inline:
        algorithmExpression: entity_stu_ques_knowledge_${student_id % 100}
        shardingColumn: student_id
  entity_student_error_exe:
    actualDataNodes: ms_answer.entity_student_error_exe_${0..99}
    keyGeneratorColumnName: id
    logicTable: entity_student_error_exe
    tableStrategy:
      inline:
        algorithmExpression: entity_student_error_exe_${student_id % 100}
        shardingColumn: student_id
  entity_student_exercise:
    actualDataNodes: ms_answer.entity_student_exercise_${2015..2019}_${0..49}
    keyGeneratorColumnName: id
    logicTable: entity_student_exercise
    tableStrategy:
      complex:
        algorithmClassName: io.shardingsphere.api.algorithm.sharding.complex.ComplexAnswerShardingAlgorithm
        shardingColumns: year,class_id,student_id        
  cms_brush_questions_correct:
    actualDataNodes: ms_answer.cms_brush_questions_correct
    logicTable: cms_brush_questions_correct

Thx.

**Comment by terrymanu** [comment] 2019-07-29 09:59
Can you try to example first?
And you may provide necessary information followed the template below:

**Comment by terrymanu** [comment] 2019-07-29 10:00
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by Myshiner** [comment] 2019-07-29 10:12
**Which version of ShardingSphere did you use?**
we used ShardingSphere v3.1.0.
**Which project did you use? Sharding-JDBC or Sharding-Proxy?**
Sharding-Proxy.
**Expected behavior**
Selection query should be routed to slave node in sharding.
**Actual behavior**
Selection query should routed to master node in sharding.

so in sharding the master-slave didn't work.

**Comment by Myshiner** [comment] 2019-07-29 10:38
query example:
select year,subject_id from link_respackage_student where student_id=21210301 order by id desc;
This query should be routed to slave node "slave_lessondb_0" node instead of master node "ms_lessones", but in the logs i got "2019-07-29 18:33:20.543 [pool-8-thread-1] INFO  ShardingSphere-SQL - Actual SQL: **ms_lessones** ::: select year,subject_id from link_respackage_student_1 where student_id=21210301 order by id desc"

**Comment by terrymanu** [comment] 2019-07-30 02:47
Can you use 4.0.0-RC1 to test  it again?

**Comment by Myshiner** [comment] 2019-07-30 03:19
Yes, i can, i wondered if it works on your side ?

**Comment by Myshiner** [comment] 2019-07-30 06:52
I used 4.0.0-RC1 just now, and even i can't start the process, it threw errors as following.
**Exception in thread "main" java.lang.IllegalArgumentException: Type is required.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at org.apache.shardingsphere.api.config.TypeBasedSPIConfiguration.<init>(TypeBasedSPIConfiguration.java:43)
        at org.apache.shardingsphere.orchestration.reg.api.RegistryCenterConfiguration.<init>(RegistryCenterConfiguration.java:76)
        at org.apache.shardingsphere.orchestration.yaml.swapper.RegistryCenterConfigurationYamlSwapper.swap(RegistryCenterConfigurationYamlSwapper.java:48)
        at org.apache.shardingsphere.orchestration.yaml.swapper.OrchestrationConfigurationYamlSwapper.swap(OrchestrationConfigurationYamlSwapper.java:46)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCenter(Bootstrap.java:100)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:75)**

**Comment by Myshiner** [comment] 2019-07-30 08:38
In version 4.0.0-RC1 of sharding-proxy, I got the errors "Exception in thread "main" java.lang.IllegalArgumentException: Type is required." just when i config orchestration in server.yaml file, or it worked without orchestration configuration.

**Comment by terrymanu** [comment] 2019-07-30 08:54
Maybe you need to reference document to know how to config it

**Comment by Myshiner** [comment] 2019-07-30 09:15
Yup, i did follow the official document, and it's in accord with the source code configuration.
orchestration:
  name: orchestration_ds
  overwrite: true
  registry:
    serverLists: 192.168.0.11:2181
    namespace: orchestration

**Comment by Myshiner** [comment] 2019-07-30 10:24
I tested few times to prove that sharding-proxy v3.1.0 didn't support master-slave in sharding and v4.0.0-RC1 did support. But there are configurations in the official document. 
![image](https://user-images.githubusercontent.com/48242833/62121922-2a6d8e80-b2f7-11e9-83ae-6dd332fbac94.png)

**Comment by Myshiner** [comment] 2019-07-30 10:24
![image](https://user-images.githubusercontent.com/48242833/62121965-41ac7c00-b2f7-11e9-94fb-9f1d72d0da6b.png)

**Comment by terrymanu** [comment] 2019-07-31 02:49
For 3.x, you need follow 3.x's document.
FYI: https://shardingsphere.apache.org/document/legacy/3.x/document/en/overview/

Any way, we only focus 4.x for now. So I just close this issue now.

**Closed by terrymanu** 2019-07-31 02:49 UTC
Labels: need feedback

**Comment by Myshiner** [comment] 2019-07-31 03:17
Yes, i did follow 3.x's doc in v3.1.0 and still didn't work without any errors and warnings.

**Comment by Myshiner** [comment] 2019-07-31 06:45
The official doc provide "sharding and read-write splitting" configuration example , but it's different from the source code configure.
