### ISSUE TITLE
version 3.1.0  may route wrong and cause memory leak when tomcat start （ A sql route wrong to 1002 table ）

### ISSUE THREAD

**Issue by Ah39** [apache/incubator-shardingsphere#2995] opened 2019-09-06 17:03 UTC
**Two datasources
DataSource A**
100 druid connection 
1002 tables in a DB
DataSource B

![image](https://user-images.githubusercontent.com/2367243/64446073-81426100-d10a-11e9-8bce-d06060fd6c80.png)

### It Dos not happen every time（ when the application start ）

![image](https://user-images.githubusercontent.com/2367243/64449129-dcc41d00-d111-11e9-9543-dd82e339d9bd.png)
![image](https://user-images.githubusercontent.com/2367243/64449200-fe250900-d111-11e9-8f23-33c1e6dd26c8.png)

may cause by here 
![image](https://user-images.githubusercontent.com/2367243/64446322-19404a80-d10b-11e9-8d1e-d01ef5bc5c9f.png)

**Comment by terrymanu** [comment] 2019-09-07 02:19
Can you try version 4.0.0-RC2?

**Comment by Ah39** [comment] 2019-09-09 08:25
multithread call when tomcat started，have the possiblity reproduce.
call getByid in PostContrust ,fixed the problem

**Comment by terrymanu** [comment] 2019-09-11 13:59
Is it in version 4.0.0-RC2 or 3.1.0?

**Comment by Ah39** [comment] 2019-09-12 06:46
my version 3.1.0 
dont test 4.0.4-RC2

**Comment by KomachiSion** [comment] 2019-09-17 01:16
@Ah39 , What's your sharding configuration and your execute SQL

**Comment by Ah39** [comment] 2019-09-17 02:39
sharding.jdbc.config.sharding.tables.t_file.actual-data-nodes=ds_0.t_xxx1_$->{0..1001}
sharding.jdbc.config.sharding.tables.t_file.table-strategy.inline.sharding-column=xxx1_id
sharding.jdbc.config.sharding.tables.t_file.table-strategy.inline.algorithm-expression=t_xxx1_$->{xxx1_id % 1001}

sharding.jdbc.config.sharding.tables.t_command.actual-data-nodes=ds_1.t_xxx2_$->{0..1001}
sharding.jdbc.config.sharding.tables.t_command.table-strategy.inline.sharding-column=xxx2_id
sharding.jdbc.config.sharding.tables.t_command.table-strategy.inline.algorithm-expression=t_xxx2_$->{xxx2_id % 1001}

sharding.jdbc.config.sharding.tables.t_job.actual-data-nodes=ds_1.t_xxx3_$->{0..1001}
sharding.jdbc.config.sharding.tables.t_job.table-strategy.inline.sharding-column=xxx3_no
sharding.jdbc.config.sharding.tables.t_job.table-strategy.inline.algorithm-expression=t_xxx3_$->{xxx3_no % 1001}

sharding.jdbc.config.sharding.tables.t_job_result.actual-data-nodes=ds_1.t_xxx4_$->{0..1001}
sharding.jdbc.config.sharding.tables.t_job_result.table-strategy.inline.sharding-column=xxx4_no
sharding.jdbc.config.sharding.tables.t_job_result.table-strategy.inline.algorithm-expression=t_xxx4_$->{xxx4_no % 1001}


SQL  forexample ：get by xxx2_id （select * from t_xxx2 where xxx2_id=12343432432 )

@KomachiSion

**Comment by KomachiSion** [comment] 2019-09-20 10:13
@Ah39 , Can you try to use 4.0.0-RC2. 
In new version, the cache has changed to soft reference.

**Comment by Ah39** [comment] 2019-09-24 07:31
> @Ah39 , Can you try to use 4.0.0-RC2.
> In new version, the cache has changed to soft reference.

SQLParseResultCache may still have the problem

**Comment by KomachiSion** [comment] 2019-09-27 00:59
Sorry @Ah39, I can't reproduce your problem in my environment. Can you set `sql.show=true` and make sure the actual SQL is routed to 1002 tables.

BTW, your SQL is `select * from t_xxx2 where xxx2_id=12343432432`, can you change to use placeholder like `select * from t_xxx2 where xxx2_id=?` then retry?

**Comment by terrymanu** [comment] 2019-10-09 03:41
version 3.x is too old and it is not apache release, we cannot maintain any more.
I just close this issue.
Please have a test on 4.x

**Closed by terrymanu** 2019-10-09 03:41 UTC
Labels: volunteer wanted
