### ISSUE TITLE
sharding-jdbc 3.0.0 can not use flyway

### ISSUE THREAD

**Issue by MoonPaul** [apache/incubator-shardingsphere#2488] opened 2019-06-03 02:17 UTC
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by MoonPaul** [comment] 2019-06-03 02:30
sharding-jdbc 3.0.0
spring-boot 2.1
flyway 5.2.1
can not execute the program with error:
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to restore original schema
---------------------------------
SQL State  : null
Error Code : 0
Message    : setCatalog

	at org.flywaydb.core.internal.database.base.Connection$2.call(Connection.java:171) ~[flyway-core-5.2.1.jar:na]
	at org.flywaydb.core.internal.database.base.Connection$2.call(Connection.java:165) ~[flyway-core-5.2.1.jar:na]
	at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74) ~[flyway-core-5.2.1.jar:na]
	at org.flywaydb.core.internal.database.base.Connection.restoreOriginalSchema(Connection.java:165) ~[flyway-core-5.2.1.jar:na]
	at org.flywaydb.core.internal.database.base.Connection.close(Connection.java:159) ~[flyway-core-5.2.1.jar:na]
	at org.flywaydb.core.internal.database.base.Database.close(Database.java:473) ~[flyway-core-5.2.1.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1716) ~[flyway-core-5.2.1.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1341) ~[flyway-core-5.2.1.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	... 18 common frames omitted
Caused by: java.sql.SQLFeatureNotSupportedException: setCatalog
	at io.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationConnection.setCatalog(AbstractUnsupportedOperationConnection.java:96) ~[sharding-jdbc-core-3.0.0.jar:na]
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.doChangeCurrentSchemaOrSearchPathTo(MySQLConnection.java:57) ~[flyway-core-5.2.1.jar:na]
	at org.flywaydb.core.internal.database.base.Connection$2.call(Connection.java:169) ~[flyway-core-5.2.1.jar:na]
	... 28 common frames omitted
it looks like sharding-jdbc can not work with flyway or i make a mistake?
if sharding 3.0.0 can not work with flyway, is there any other db schema control tools works with sharding  well?
or i need to modify the code in sharding-jdbc to support a db scheam control tool?

**Comment by terrymanu** [comment] 2019-06-03 03:16
Caused by: java.sql.SQLFeatureNotSupportedException: setCatalog

Some jdbc feature we are not support yet. If someone want implement this, can create a new issue.
I just keep open this issue for few days, if nobody interested with this, I will close later.

**Comment by mwylaoma** [comment] 2019-06-12 06:18
Please be sure to support this. Because we use this to update database in our project

**Comment by terrymanu** [comment] 2019-06-21 02:06
I just close this issue because to implement all JDBC interface for sharding is too much work to do.
If somebody want to implement one of unimplement method, please contact us by a feature request and talk how to implement method technically.

**Closed by terrymanu** 2019-06-21 02:06 UTC
Labels: volunteer wanted

**Comment by kkliuxin** [comment] 2020-06-04 08:53
这个还是没有办法解决吗？

**Comment by hi-mamba** [comment] 2020-07-02 03:57
遇到同样的问题
sharding-jdbc 3.1.0
flyway 5.2.4

**Comment by HinsYang** [comment] 2020-09-09 09:58
已解决
sharding-jdbc 3.1.0
flyway 5.2.4升级到6.5.5

**Comment by 844704781** [comment] 2020-12-29 07:31
> 已解决
> sharding-jdbc 3.1.0
> flyway 5.2.4升级到6.5.5

有案例吗

**Comment by super0086** [comment] 2022-03-04 08:26
sharding-jdbc 3.1.0
flyway 5.2.4升级到6.5.5

真的能解决吗？
