### ISSUE TITLE
null and pagination question

### ISSUE THREAD

**Issue by WillWei1983** [apache/incubator-shardingsphere#2538] opened 2019-06-11 10:22 UTC
## Question

I am using the sharding-proxy, the PreparedStatement setString, I set the field to be null object not the 'null' string, the sharding-proxy will treat it as a string to be inserted into table,which is not my expected result is also not the same as in jdbc.
for the pagination, it is not support the sql like  'limit 20 offset 0' ;only support the 'limit 0,20'. if this limit offset statement can be supported in the future?

**Comment by terrymanu** [comment] 2019-06-11 10:25
For 1st question, it maybe a bug, we will investigate it.
For 2nd question, what database do you use?

**Comment by WillWei1983** [comment] 2019-06-11 10:41
2nd question,  I am using Mysql.

**Comment by tuohai666** [comment] 2019-06-11 10:43
What's the version of sharding-proxy?

**Comment by WillWei1983** [comment] 2019-06-11 10:46
> What's the version of sharding-proxy?

I am using the shardingsphere4.0.0-RC1. OS:Ubuntu 18.04.

**Comment by terrymanu** [comment] 2019-06-11 16:57
It is missing test case for limit and offset. I just add it on 6981f690ae2864fa4927fdb5fc74f795a981191e, the test case is ok for this limit and offset.

**Comment by WillWei1983** [comment] 2019-06-12 01:33
It seems that you guys have fixed this. May I know when this fixed will be in the release version of the product?

**Comment by terrymanu** [comment] 2019-06-12 03:32
No release plan.
We will investigate first question soon.

**Comment by tuohai666** [comment] 2019-06-12 04:07
I don't think sharding-proxy will treat null to 'null'. I have tested with jdbc parameter **&useServerPrepStmts=true&cachePrepStmts=true** and without this parameter, the result proofed the value is correct.
If you insist your point of view, please provide more evidence, like codes, configuration, query result.

But when I inserted null value, there fired an Exception, I'll fix it.

**Comment by WillWei1983** [comment] 2019-06-12 04:29
I config the HikariConfig as belows
`
config.addDataSourceProperty("useServerPrepStmts",false);
  config.addDataSourceProperty("rewriteBatchedStatements",true);
`
and in the PreparedStatement, I add use the setString(index,null) for the field in case it does not have a value for it.
then addBatch() for the PreparedStatement
when it comes to 2w records, I execute the statement by using the PreparedStatement executeLargeBatch() method.

Normally, I won't insert record by this way,  this is for my testing on data migration for nearly 1.2亿record.
BTW, event by using this 'batch' way, it seems that it dose not improve the performance when using the sharding. it only improve performance when inserting to a single table directly using jdbc, but that is not my purpose. if this lead to this issue ,I will revise the data migration code to etl the record one by one.

**Comment by tuohai666** [comment] 2019-06-12 04:49
Can you point out the position when the problem occered between the sentences?

**Comment by tuohai666** [comment] 2019-06-12 08:21
The question is straight forward: what do you see from the screen after your database query?
I don't think sharding-proxy will convert null to 'null'. If you insist your point of view, you can provide screen shot.
Also, you can try 4.0.0-RC2, at least I can't reproduce the issue on this version.
Anyway it's reasonable to close this issue.

**Closed by tuohai666** 2019-06-12 08:21 UTC
Labels: bug, proxy
