### ISSUE TITLE
what is the lifecycle of hint

### ISSUE THREAD

**Issue by leehom** [apache/incubator-shardingsphere#1620] opened 2018-12-14 02:26 UTC
## Question
what is the lifecycle of hint,  within transaction，session, such as mybatis sql session，or connection?
how to control it myself?  
I use hint as sharding strategy，I found hint clear over transaction if existed，or over mybatis sql session，
i use aop that intercepting service and dao to set and clear hint，but it is a bad smell code

**Comment by leehom** [comment] 2018-12-14 02:31
when using thead pool make thinks more worst，threadlocal would exist in thread within the pool

**Comment by cherrylzhao** [comment] 2018-12-15 05:07
hi，we only call HintManager.clear within shardingConnection.close，so this is beyond on the timing when client invoke. generally if u begin a transaction using spring，springTransactionMaanger will commit the connection，then close it

**Comment by leehom** [comment] 2018-12-15 07:36
"springTransactionMaanger will commit the connection，then close it"
Did you mean it denpends SpringTransactionManager(short for tm) or some other tms to close the connection, and then clear the hint.
i think, in some time, such as db connection pool, tm would not close the connection.
in fact,i found that condition exsist, that is to say，hints would keep in the thread that managed by pool，it would shared by multi request, that made things confused.

**Comment by cherrylzhao** [comment] 2018-12-15 08:02
yes, SpringTransactionManager will invoke cleanAfterCompletion method to release connection, you can see the source `AbstractPlatformTransactionManager#processCommit`.
in factor, when we call datasource.close method, datasource pool  just change the connection status to Not use, physical connection to database will keep.

**Comment by cherrylzhao** [comment] 2018-12-15 08:08
and you found some scenario thread local haven't clear, I think that is based on you set of the hintManager, if you set the threadLocal many times, but Sharding connection only close once, this will happen.

**Comment by leehom** [comment] 2018-12-17 01:30
can i make a summary，
first, shardingConnection.close would not be invoked, if Connection is managed by pool, then hint dosen't clear and keep in thread
second, hints would keep in the thread that managed by pool, and be shared by multi requests,  that made things confused.

**Comment by terrymanu** [comment] 2019-02-12 07:33
@leehom I cannot get your point. Hint is keep same lifecycle with connection, if connection closed, hint should be closed.
Can you make an example for if user need hold hint even connection closed?

> i think, in some time, such as db connection pool, tm would not close the connection.
If connection did not close, hint also did not close automatically, user can close it by themselves. Any question here?

> first, shardingConnection.close would not be invoked, if Connection is managed by pool, then hint dosen't clear and keep in thread
Why? Whatever connection is managed by pool or not, they just use JDBC to call connection.close, will close hint together.

> second, hints would keep in the thread that managed by pool, and be shared by multi requests, that made things confused.
I don't think so. Hint should not cross thread.

**Comment by terrymanu** [comment] 2019-02-18 04:01
If no update any more, I will close this issue tomorrow.

**Comment by leehom** [comment] 2019-02-18 08:40
**I cannot get your point. Hint is keep same lifecycle with connection, if connection closed, hint should be closed.**

the point is connection don't close when it is managed by pool,  and then thread isn't clear, hints is keeped in thread local，so hints is not clear.

**Comment by terrymanu** [comment] 2019-02-18 14:52
> the point is connection don't close when it is managed by pool, and then thread isn't clear, hints is keeped in thread local，so hints is not clear.

Sharding-JDBC do not care the connection is closed or hold by pool, it just care the connection is closed logically.
When user call `close` method, Sharding-JDBC will call `close` method of all data sources which it managed(for pool, it returned to pool; for raw jdbc, it closed, but it doesn't matter), the thread local is cleared.
So, any problem here? Or can you provide a example and paste github link here?

**Comment by leehom** [comment] 2019-02-19 01:15
I can borrow a blog to show what i mean，and it include code example
https://blog.csdn.net/qq_33522040/article/details/85322094

the key is “because of reusing the thread, it make the hints not  being cleared”

**Comment by terrymanu** [comment] 2019-02-19 06:08
> the key is “because of reusing the thread, it make the hints in the thread not being cleared”

How to reusing the thread without connection closed? If user really meet this scene, user can call `HintManager.close()` method to clear hint info by themselves.

ShardingSphere provide to way to clear hint info.

1. User call `HintManager.close()`
2. User call `connection.close()`

Do you want more way to clear hint info?

**Comment by leehom** [comment] 2019-02-20 08:27
> 
> 
> > the key is “because of reusing the thread, it make the hints in the thread not being cleared”
> 
> How to reusing the thread without connection closed? If user really meet this scene, user can call `HintManager.close()` method to clear hint info by themselves.
> 
> ShardingSphere provide to way to clear hint info.
> 
>     1. User call `HintManager.close()`
> 
>     2. User call `connection.close()`
> 
> 
> Do you want more way to clear hint info?

for  1。 User call `HintManager.close()`， yes，we now manage hints by myself，calling`HintManager.close()`，but at the same time we remove the `HintManager.close()` in `connection.close()` (we not use ss v3.0.0)

for 2. User call `connection.close()`， it is another bug，db connect is managed by pool too，connection.close() should not be called when the db connection retrieved

**Comment by terrymanu** [comment] 2019-02-22 05:20
> for 2. User call `connection.close()`， it is another bug，db connection is managed by pool too，connection.close() should not be called when the db connection retrieved

As I said before: Sharding-JDBC do not care the connection is closed or hold by pool, it just care the connection is closed logically.

**Comment by terrymanu** [comment] 2019-02-22 05:24
I still cannot get your point. I have already explain how to work for data source pool, is it clear?

Can you provide a example and paste github link to explain what is the problem you met?

**Comment by terrymanu** [comment] 2019-02-28 23:31
@leehom If no other question, can you close this issue?

**Comment by terrymanu** [comment] 2019-03-01 15:28
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Closed by terrymanu** 2019-03-01 15:28 UTC
Labels: need feedback
