### ISSUE TITLE
cpu load 100% when using sqlstatement cache

### ISSUE THREAD

**Issue by erstens** [apache/incubator-shardingsphere#2997] opened 2019-09-07 02:37 UTC
**jstack**

`"DubboServerHandler-172.16.42.151:9503-thread-483" #734 daemon prio=5 os_prio=0 tid=0x00007f36bc17e000 nid=0x4c92 runnable [0x00007f36465c1000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.commons.collections4.map.AbstractHashedMap.getEntry(AbstractHashedMap.java:461)
	at org.apache.commons.collections4.map.AbstractReferenceMap.getEntry(AbstractReferenceMap.java:427)
	at org.apache.commons.collections4.map.AbstractReferenceMap.get(AbstractReferenceMap.java:244)
	at org.apache.shardingsphere.core.parse.cache.ParsingResultCache.getSQLStatement(ParsingResultCache.java:53)
	at org.apache.shardingsphere.core.parse.SQLParsingEngine.getSQLStatementFromCache(SQLParsingEngine.java:69)
	at org.apache.shardingsphere.core.parse.SQLParsingEngine.parse(SQLParsingEngine.java:56)
	at org.apache.shardingsphere.core.route.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:78)
	at org.apache.shardingsphere.core.route.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:64)
	at org.apache.shardingsphere.core.PreparedQueryShardingEngine.route(PreparedQueryShardingEngine.java:60)
	at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:64)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.shard(ShardingPreparedStatement.java:224)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:109)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:692)
...........
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:776)
.........
`

**top threads**
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                             
19602 root      20   0 8773700 2.766g  23436 R 94.1 17.8   8:29.27 java                                                
19617 root      20   0 8773700 2.766g  23436 R 88.2 17.8  18:27.23 java                                                
19606 root      20   0 8773700 2.766g  23436 R 47.1 17.8  12:36.25 java                                                
19611 root      20   0 8773700 2.766g  23436 R 41.2 17.8   7:58.80 java                                                
19608 root      20   0 8773700 2.766g  23436 R 29.4 17.8  24:20.39 java                                                
19612 root      20   0 8773700 2.766g  23436 R 29.4 17.8  31:49.70 java                                                
19601 root      20   0 8773700 2.766g  23436 R 23.5 17.8   0:00.82 java 

**version**
`<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>4.0.0-RC1</version>
        </dependency>`

please help me ,thanks all .

**Comment by terrymanu** [comment] 2019-09-07 03:29
Can you try version 4.0.0-RC2?

**Comment by erstens** [comment] 2019-09-07 05:05
Trouble giving a source of relevant changes link？thanks

**Comment by Ah39** [comment] 2019-09-07 08:56
https://github.com/apache/incubator-shardingsphere/issues/2965
 ParsingResultCache may have another problem，because of gc

**Comment by erstens** [comment] 2019-09-07 10:14
emm,i find `org.apache.shardingsphere.api.config.sharding.TableRuleConfiguration.logicIndex` is removed,it is nouse ?

**Comment by erstens** [comment] 2019-09-10 03:31
in the cahe using apache AbstractHashedMap,why not `ConcurrentHashMap` ?

**Comment by terrymanu** [comment] 2019-09-11 14:00
Can it reproduce on 4.0.0-RC2?

**Comment by terrymanu** [comment] 2019-09-21 02:23
Closed for long time no response, if issue still existed, please create a new issue.

**Comment by xiyelife** [comment] 2020-01-09 16:05
I have  the same problem, and plan to use guave cache instead of AbstractHashedMap

**Comment by terrymanu** [comment] 2020-01-09 16:07
@xiyelife Thank you, I just assign this issue to you.

**Closed** 2020-01-13 09:53 UTC
Labels: SQL parse, enhancement

**Comment by zljgit** [comment] 2020-07-31 02:33
> **jstack**
> 
> `"DubboServerHandler-172.16.42.151:9503-thread-483" #734 daemon prio=5 os_prio=0 tid=0x00007f36bc17e000 nid=0x4c92 runnable [0x00007f36465c1000] java.lang.Thread.State: RUNNABLE at org.apache.commons.collections4.map.AbstractHashedMap.getEntry(AbstractHashedMap.java:461) at org.apache.commons.collections4.map.AbstractReferenceMap.getEntry(AbstractReferenceMap.java:427) at org.apache.commons.collections4.map.AbstractReferenceMap.get(AbstractReferenceMap.java:244) at org.apache.shardingsphere.core.parse.cache.ParsingResultCache.getSQLStatement(ParsingResultCache.java:53) at org.apache.shardingsphere.core.parse.SQLParsingEngine.getSQLStatementFromCache(SQLParsingEngine.java:69) at org.apache.shardingsphere.core.parse.SQLParsingEngine.parse(SQLParsingEngine.java:56) at org.apache.shardingsphere.core.route.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:78) at org.apache.shardingsphere.core.route.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:64) at org.apache.shardingsphere.core.PreparedQueryShardingEngine.route(PreparedQueryShardingEngine.java:60) at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:64) at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.shard(ShardingPreparedStatement.java:224) at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:109) at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:692) ........... at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:776) ......... `
> 
> **top threads**
> PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
> 19602 root 20 0 8773700 2.766g 23436 R 94.1 17.8 8:29.27 java
> 19617 root 20 0 8773700 2.766g 23436 R 88.2 17.8 18:27.23 java
> 19606 root 20 0 8773700 2.766g 23436 R 47.1 17.8 12:36.25 java
> 19611 root 20 0 8773700 2.766g 23436 R 41.2 17.8 7:58.80 java
> 19608 root 20 0 8773700 2.766g 23436 R 29.4 17.8 24:20.39 java
> 19612 root 20 0 8773700 2.766g 23436 R 29.4 17.8 31:49.70 java
> 19601 root 20 0 8773700 2.766g 23436 R 23.5 17.8 0:00.82 java
> 
> **version**
> `<dependency> <groupId>org.apache.shardingsphere</groupId> <artifactId>sharding-jdbc-core</artifactId> <version>4.0.0-RC1</version> </dependency>`
> 
> please help me ,thanks all .

看上去是 SQLParseResultCache
    private final Map<String, SQLStatement> cache = new ReferenceMap<>(AbstractReferenceMap.ReferenceStrength.SOFT, AbstractReferenceMap.ReferenceStrength.SOFT, 65535, 1);
导致死循环

**Comment by xiyelife** [comment] 2020-08-10 02:54
Please use the 4.0.1 or higher version. It has been fixed by guava cache.
